### ISSUE TITLE
Add dosctrings everywhere in `std` and `core` libraries

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#1066]
While `forc doc` is not fully functional yet, we really should be adding docstrings to everything in the standard library.

**Comment by mitchmindtree** [comment]
Now that #2869 is implemented, now would be a great time to get started on this!

The docs are still looking quite raw today, but having fleshed out documentation in `core` and `std` would act as a great real-world test case for landing new features like doc tests, inter-module linking, etc.

**Comment by eureka-cpu** [comment]
Is this still open? I believe the docs in at least std are looking pretty good

**Comment by mitchmindtree** [comment]
Loads of the items and modules in std are still missing docs, and most of those that have docs have something like a single sentence that doesn't give much context about the purpose of the type, how to use it correctly, no examples, etc.

I think the "standard" of std docs we should hold ourselves to is Rust's std: https://doc.rust-lang.org/std/index.html. It totally outclasses us at the moment.

That said, this issue is a bit vague - maybe we're better off opening a tracking issue that sets a standard for how we expect std items to be documented, and a checklist for going through them? All methods/functions should likely have examples at least, however we'd likely be better off tackling #3176 before adding too many examples, otherwise they'll almost certainly fall out of date without close attention.

**Comment by eureka-cpu** [comment]
> Loads of the items and modules in std are still missing docs, and most of those that have docs have something like a single sentence that doesn't give much context about the purpose of the type, how to use it correctly, no examples, etc.
> 
> I think the "standard" of std docs we should hold ourselves to is Rust's std: https://doc.rust-lang.org/std/index.html. It totally outclasses us at the moment.
> 
> That said, this issue is a bit vague - maybe we're better off opening a tracking issue that sets a standard for how we expect std items to be documented, and a checklist for going through them? All methods/functions should likely have examples at least, however we'd likely be better off tackling #3176 before adding too many examples, otherwise they'll almost certainly fall out of date without close attention.

@gr00vytvniks this could be a good issue for you to take on.

**Comment by gr00vytvniks** [comment]
If this is still a relevant issue I'd be happy to take it on :)

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/4830
