### ISSUE TITLE
Handle arrays in `storage` declarations

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1182]

**Comment by ironcev** [comment]
@tritao It is still an issue, arrays are currently not supported. But it ahould be closed in favor of [Storage 3.0](https://github.com/FuelLabs/sway-rfcs/pull/40), because there is no sense in implementing array support now, just to throw it away once we implement Storage 3.0, which is anyhow a priority.

So I'll close the issue.
