### ISSUE TITLE
Introduce `--contract` and `--script` to `forc init`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1186]
`$ forc init --script` -> create an empty script. Question: is a Rust test harness required with this?
`$ forc init --contract` -> create two Sway files: one for the ABI and one for its implementation. Also create a test harness populated with boilerplate code. 
We could also do `--predicate` and `--library`.

The default should probably be a contract.

**Comment by nfurfaro** [comment]
>create an empty script. Question: is a Rust test harness required with this?

I would say yes. While we may choose to put simple script tests in the e2e test suite for our project, most users will only have the SDK for testing so might as well make it easy for them.
The sway test suite is a special use case, so deleting a bit of code that's not needed isn't a big deal; I'm already deleting the `tests` directory & `cargo.toml` at a minimum when setting up new test projects.

**Comment by Braqzen** [comment]
The library could be `forc init --lib <name of lib>` or `forc init --library <name of lib>`
```
library abi;

abi SomeName {
    fn some_action(parameter: type) -> bool {}
}
```
The current `forc init` would need to remove the Cargo.toml file and remove the Sway dependency in Forc.toml + remove the tests directory (all according to the docs) iirc, moreover remove the impl since it starts as a contract

The contract could be `forc init <name of contract>` or `forc init --contract <name of contract>`
```
contract;

use abi::SomeName;

impl SomeName for Contract {
    fn some_action(parameter: type) -> bool {
        // maybe do something with parameter here
        true
    }
}
```
Need to link the abi (library) in Forc.toml too and remove the default abi that it provides since it starts as a contract

The script could be `forc init --script <name of script>`
```
script;

use abi::SomeName;

fn main() -> bool {
    let caller = abi(SomeName, <contract address>);  // new contract syntax may be used instead, soon
    let success = caller.some_action(<some parameter>);

    success
}
```
Need to link the abi (library) in Forc.toml too and remove the default abi that it provides since it starts as a contract
