### ISSUE TITLE
Setup CI to automatically publish `forc` binary for supported architectures under each release

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1191]
It would be super useful to have the published binaries available under the "Assets" for each release here https://github.com/fuellabs/sway/releases.

Ideally this would include builds for the common Linux, macOS and Windows architectures.

I'd imagine this would look like a new github action CI job for each architecture once the "publish" conditions have been met.

It would be nice if `fuel-core` was similarly available, but this might be better off under the `fuel-core` repo.

### Useful Links

- https://trstringer.com/github-actions-create-release-upload-artifacts/
- https://github.com/johnthagen/min-sized-rust

**Comment by mitchmindtree** [comment]
This should also include builds for the new plugins, i.e. `forc-lsp` (#1179) and `forc-explore` (#1180).

**Comment by adlerjohn** [comment]
This might help: https://github.com/gakonst/foundry/blob/master/.github/workflows/release.yml

**Comment by emilyaherbert** [comment]
I'm hoping to use this feature for a workshop during EthCC in mid-July. Would it be possible to have this feature implemented by mid-June? The extra buffer time would be to allow for integration with the workshop layout, etc.

(This question is mostly poised to the void, as there is not currently someone assigned to this issue, CC @sezna @mohammadfawaz )

This issue is related: https://github.com/FuelLabs/fuels-rs/issues/237

**Comment by ra0x3** [comment]
@mitchmindtree Just FYI this issue description is so wonderful it hurts 🥲 Thanks
