### ISSUE TITLE
`forc test` should check Rust version

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1239]
Running `forc test` should check that
1. Rust exists, and
2. The version of Rust matches some supported version. Currently only 1.58 or above. Maybe warn if it's above.

**Comment by SilentCicero** [comment]
Agreed, this is a great idea.

**Comment by SilentCicero** [comment]
@adlerjohn what about a warning at `forc init` also?

**Comment by adlerjohn** [comment]
Probably a good idea for that subcommand too.

**Comment by mitchmindtree** [comment]
Looks like `cargo` supports this officially as of recently! Should hopefully make this a bit easier.

https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html#cargo-rust-version

We could possibly do something like:

1. Add our minimum supported Rust version to `forc`'s `Cargo.toml`.
2. Use `include_str!` to have `forc` include it's own cargo manifest under a `const` `&str`.
3. During `forc init`, use `toml` to deserialize the manifest and retrieve the `rust-version` field under the `[package]` table. Use the same entry under the test harness `Cargo.toml` generated by `forc init`.

That said, just because this min version works with `forc` doesn't mean it will with the SDK. Perhaps `fuels-rs` itself could expose its own min-version via a `const &str`, and then we could use that directly in `forc`? In the meantime, we should at least be sure to sync the minimum Rust version across all our repos and crates.

**Comment by SilentCicero** [comment]
Yeah, it's likely best for package level requirement.

We could add something to test, but this is usually a better route as it's more higher level.

**Comment by adlerjohn** [comment]
cc @digorithm for thoughts on how the SDK could provide some sort of guarantees around both Rust version and its own version compatibility

**Comment by mitchmindtree** [comment]
I've opened #1345 with some related ideas that might help with this.
