### ISSUE TITLE
No code formatting in generated forc CLI docs

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1246]
There is no formatting in the CLI generated example:
https://fuellabs.github.io/sway/latest/forc/commands/forc_deploy.html#examples

**Comment by adlerjohn** [comment]
There's also no code block formatting, e.g. in completions. This is most likely because the output from `--help` that's saved doesn't have things like backticks for code blocks. cc @binggh @mitchmindtree

**Comment by binggh** [comment]
will open a fix for this

**Comment by binggh** [comment]
> There's also no code block formatting, e.g. in completions. This is most likely because the output from `--help` that's saved doesn't have things like backticks for code blocks. cc @binggh @mitchmindtree

it's actually because the script was written only to check for headers, options, and arguments in mind and assumes that blocks of text in between are short form texts describing either options or arguments. In the case of `completions` there is instead a long form discussion right after the `    -s, --shell <SHELL>    [possible values: zsh, bash, fish, powershell, elvish]` option line to guide the user to set up the script. So actually there is no code block formatting done here, the script is assuming its a description of the above shell option.

We can:
1) conditionally format this within the script for this command's docs for now, or
2) move the long form discussion into `examples.rs` in the script directory instead of presenting it as a help text, then we can format it freely

**Comment by adlerjohn** [comment]
cc @JoshuaBatty since he led the completions effort for opinions

**Comment by JoshuaBatty** [comment]
So the current implementation of `forc completions --help` is modeled after the `rustup help completions` command in Rust.

One positive about have such detailed documentation printed in the terminal is you can quickly generate and install the completion scripts for your shell. Without this, only seeing ` -s, --shell <SHELL> [possible values: zsh, bash, fish, powershell, elvish]` when typing `forc completions --help` doesn't show any real information about how to actually install the script for your shell. 

That being said, its pretty easy to find these instructions in the sway book so i'm happy to go with option 2.
