### ISSUE TITLE
Create a new command for `forc` which is used to create template projects e.g. `forc init --template erc-20`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1356]
This issue expands on [Introduce --contract and --script to forc init #1186](https://github.com/FuelLabs/sway/issues/1186).

#1186 is an extension of the current implementation, that defaults to a contract-esque format with a simple `abi` and `impl` block, which is meant to allow users to create an empty project based on the passed in program type e.g. `forc init --<program type> <name of project>`. 

This new issue is meant to allow the creation of various different template projects and thus should not be limited to the proposed usage in the title. 
The template should allow the user to e.g. create a template for an ERC-20 token (but in Sway) or a DEX etc.

The purpose of this is 2 fold
1. It can be used for learning purposes and thus demonstrates a possible project structure for each program type
2. Bootstraps the development process by creating the generic boilerplate for common programs

**Comment by mitchmindtree** [comment]
Just a heads up that we actually already have a `forc init --template <template-source> <new-project-name>` command! That said, it's still a little rough around the edges.

I love your idea of desugaring the `--contract`, `--library`, etc flags down to the equivalent template command though! E.g. `forc init --contract <new-contract-name>` becomes `forc init --template default-contract <new-contract-name>` under the hood. I think that makes a lot of sense.

Perhaps as a first step to this we could add these default project types under the `examples/` directory? I believe that's where forc currenly pulls templates from when the `--template` flag is specified.

Just as a heads up, the plan is to eventually expand `--template` to support arbitrary git repos so that 3rd parties can write custom templates too.

**Comment by Braqzen** [comment]
Closing issue as a template command has been implemented in some other issue.
