### ISSUE TITLE
Use the new `jnzi` opcode in the compiler

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1412]
https://github.com/FuelLabs/fuel-specs/pull/306 introduces a new `jnzi` opcode that is similar to `jnei` but uses an 18 bit immediate instead of 12. This allows larger bytecodes to be formed. The natural way of using this new opcode is to only use it if needed. That is, continue using `jnei` if the immediate needed fits in 12 bits and switch to `jnzi` otherwise. To use `jnzi`, the two registers previously used in `jnei` will need to be compared before passing the result into `jnzi`.

Of course, `jnzi` won't work before it is actually implemented in the VM.

There is no need to enable `jnzi` in `asm` blocks because we don't support jumps there anyways.

**Comment by otrho** [comment]
Looking at the ASMgen for conditional branches we're currently using a `JNEI [cond] $one [false-block-label]` which is mildly remarkable because it assumes a `true` boolean is 1.  Perhaps this is OK.  But a better default might be `JNZI [cond] [true-block-label]` to get us both 'true-is-any-non-zero' and the extra jump distance.

Also, the next logical solution for needing to jump further than 12 bits away is chaining, which I think some 8 bit architectures do.  Jump to another hardcoded jump instruction.
