### ISSUE TITLE
`forc test` doesn't return with error code if Cargo manifest is invalid

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1464]
CI is actually failing on [89f2ff1](https://github.com/FuelLabs/sway/pull/1461/commits/89f2ff1979ee4bbf0f381470e6271a603dedb4ba): https://github.com/FuelLabs/sway/runs/6276075112?check_suite_focus=true (see "Run test project's test suite" job).

```
error: failed to parse manifest at `/home/runner/work/sway/sway/test-proj/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  TOML parse error at line 20, column 1
     |
  20 | \n[workspace]
     | ^
  Could not parse the line
```

But `forc test` doesn't actually return an error code so it's not picked up by CI. This is a bug in `forc.`

_Originally posted by @adlerjohn in https://github.com/FuelLabs/sway/pull/1461#pullrequestreview-960645066_

**Comment by kayagokalp** [comment]
Maybe I can put down my thought process and we can discuss it. I believe this is happening because the return code of the child process (cargo test process that is created from the forc test command) is currently not fetched. To test this I will be doing:

- [ ] Create the test-proj like the CI
- [ ] Create a typo in the Cargo.toml in the test-proj
- [ ] Run `forc test`
- [ ] Check the return code (I am on a mac so I will try to get it with `echo $?`)

If I can get a non-zero error code with an invalid Cargo.toml => 👍
