### ISSUE TITLE
`sway-parse` only lexes comments, and doesn't give spans

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#1517]
Blocker for handling comments in `swayfmt` v2

At some point we will need to find a way to handle comments so that we get types for `comment` & `multiline comment` as well as the spans. We'll need this if we want to have reformatting features for comments like: `wrap comments` or for reformatting `multiline comments` to normal comments.

**Comment by mohammadfawaz** [comment]
Hmmm I don't remember having trouble with the new parser and comments. Can you show specifically what's not working?

**Comment by eureka-cpu** [comment]
> Hmmm I don't remember having trouble with the new parser and comments. Can you show specifically what's not working?

It's not that it's not working per-say, rather that it's just not there at all.
In order to reformat comments, we need handling of comments from the parser. The only thing I can find is an error `UnclosedMultilineComment`, which is a variant of `token::LexErrorKind`.

**Comment by eureka-cpu** [comment]
To be specific we would just need the type of comment, multiline or not, and the span.

**Comment by eureka-cpu** [comment]
NVM, found the function `token::lex()` that handling comments, but it's handling comments in a similar way that the current formatter handles them. I was under the impression we would get comment handling as items from the ast.

**Comment by eureka-cpu** [comment]
Closing this since my initial statement was incorrect, and will bikeshed w/ tooling on how to proceed when the time comes. Thanks @mohammadfawaz !

**Comment by eureka-cpu** [comment]
@sezna @mitchmindtree for more insight if you can provide it!

**Comment by eureka-cpu** [comment]
I don't mind taking this on at some point as well, just trying to get more information on this thread.

**Comment by mitchmindtree** [comment]
> I was under the impression we would get comment handling as items from the ast.

@eureka-cpu just to clarify, note that there's a couple of "parse" phases in sway:

1. The `sway-parse` crate's `parse_file` function, which parses a string assumed to represent the source of a `Module`.
2. The `sway-core` crate's `parse` function, which calls `sway_parse::parse_file` internally but **also** transforms the `sway_parse::Module`s into `sway_core::ParseModule`s which are a little more minimal and are stripped of tokens etc that are unnecessary for the following type-checking phase. This parse phase should probably be called `parse_to_untyped_ast` or a better name along those lines.

In the case of the formatter, it's likely best to use `sway-parse` directly as it's the closest mapping to the direct source.

W.r.t. retrieving the comments, I can understand why we might not want to include them in the parsed tree, as comments can go just about anywhere and it would likely add a lot of noise to the structure of the tree.

I wonder if instead it would be OK to add a `Comment` variant to the `TokenTree` type so that they can at least be emitted via `token::lex`? This way, perhaps the formatter could first `lex` the file and use the `TokenStream` to create a map of spans to comments, which we could then provide to the format implementations?

cc @canndrew might have some thoughts/wisdom on how to best expose comments.

**Comment by canndrew** [comment]
> I wonder if instead it would be OK to add a `Comment` variant to the `TokenTree` type so that they can at least be emitted via `token::lex`?

That would certainly be better than trying to somehow include them in the AST but it's still not ideal. It means that any parsing routine that consumes tokens from a `TokenStream` would have to skip over comments.

Maybe a better option would be to have `CommentedTokenStream` and `CommentedTokenTree` types, make `token::lex` return a `CommentedTokenStream`, and have a `CommentedTokenStream::strip_comments` method that returns a `TokenStream`. How useful would that be for `swayfmt` @eureka-cpu?
