### ISSUE TITLE
Additional example - blindauction

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#1571]
I wrote a blindauction program in sway here -> https://github.com/SwayStar123/blindauction_0_1
Maybe (after review and changes ofc) it can be added to the book as an additional example to learn from?

**Comment by SwayStar123** [comment]
Please do send PRs in that repo if you feel some formatting or something is wrong, so it will be more upto standards for getting into the book as an additional example

**Comment by Braqzen** [comment]
I'll be closing the issue because this has gone beyond a simple program into a fully developed application (WIP atm so you may not see it on master just yet). 

Examples should be limited and specific in scope rather than entire applications. The entire application should be searched for under [Sway Applications](https://github.com/FuelLabs/sway-applications).
