### ISSUE TITLE
Disallow empty enums from being created

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1697]
Currently, empty enums (or enums with no variants) have no use case in Sway. They _may_ have a use case in the distant future, but I don't expect Sway to reach that point for some time, nor do I feel that the benefit of providing features that require empty enums would be significantly beneficial to Sway from a business perspective.

For example, in Rust empty enums are considered marginal and are used in cases which would otherwise use `Infallible`: https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types

I propose that we produce an error for the declaration of empty enums.

**Comment by adlerjohn** [comment]
Related: #1679

**Comment by canndrew** [comment]
I think banning empty enums just adds inconsistency to the type system for no gain. Rust originally had a bunch of rules against empty types and matches. I implemented the changes that removed them and it mainly just consisted of deleting code.

> in Rust empty enums are considered marginal and are used in cases which would otherwise use `Infallible`:

Well, there's only one empty enum type. And since it's defined in the stdlib as `Infallible` there's rarely any need to define your own. There's certainly use-cases for it though. The most common (being where `Infallible` gets its name) is that you need to return a `Result<T, E>` to satisfy a trait method signature but your method is infallible. Another use case that used to come up in Rust a lot before const generics was for doing type-level programming. For instance, you can define type-level natural numbers with:

```
enum Zero {}
struct Succ<T> {
    phantom: PhantomData<T>,
    empty: Infallible,
}
```

Then define operations on numbers using traits. You want the types to be empty here because they're only supposed to be used for type-checking and shouldn't leak into run time.

Even if someone doesn't find these use-cases compelling I don't think that's a good reason to want to ban empty types. They're not an additional feature. They're a natural consequence of the typing rules and algorithms that we have. Supporting them just means *not* having a bunch of checks in the compiler which ban them for no reason.

I also think it's important to get this stuff right initially. Some of the changes I made to rust before 1.0 are *still* feature-gated on nightly, 6 years later, because they effect type-inference in some rare edge-cases which can lead to backwards-incompatibility.

**Comment by emilyaherbert** [comment]
Closing this because empty enums are useful now! See #3362
