### ISSUE TITLE
Tuple destructuring results in `unreachable` warnings when `_` is used

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1866]
# Reproduce

```rust
library tuples;

fn tuple() {
    let tuple = (5, true, ("Sway", 8));

    let(_, truthness, _) = tuple;
}
```

# Screenshots
![1](https://user-images.githubusercontent.com/103777923/172160781-b1f9273b-ad96-4c4a-800b-ca003e9645a7.png)

cc @sezna

**Comment by canndrew** [comment]
This doesn't look like it has anything to do with tuples. The problem (afaict) is just that it's a private function which is never used, so it's body is never executed. For example, this:

```
library stuff;

fn private_fn() {
    let _ = 4;
}

pub fn public_fn() {
    let _ = 4;
}
```

gives these errors:

```
warning
 --> .../src/main.sw:4:5
  |
2 |
3 | fn private_fn() {
4 |     let _ = 4;
  |     ---------- This returns a value of type u64, which is not assigned to anything and is ignored.
5 | }
  |
____

warning
 --> .../src/main.sw:8:5
  |
6 |
7 | pub fn public_fn() {
8 |     let _ = 4;
  |     ---------- This returns a value of type u64, which is not assigned to anything and is ignored.
9 | }
  |
____

warning
 --> .../src/main.sw:4:5
  |
2 |
3 | fn private_fn() {
4 |     let _ = 4;
  |     ---------- This code is unreachable.
5 | }
  |
____
```

The real issue here is that we don't raise a warning for unused functions but instead raise a warning for their body being unreachable.

**Comment by canndrew** [comment]
I've opened https://github.com/FuelLabs/sway/issues/1914 as a replacement.
