### ISSUE TITLE
Migrate current `forc test` logic to a new Forc plugin in `fuels-rs`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1912]
Ref: #1833

In light of `forc test` being converting to only running unit tests, migrate all current `forc test` functionality to a new `forc` plugin (name TBD, please reserve with https://github.com/FuelLabs/crate-reservations) hosted in https://github.com/FuelLabs/fuels-rs.

**Comment by mitchmindtree** [comment]
IMO we should avoid any reference to `forc` or Sway in the SDK repo at all, as the SDK should only care about being a Rust API to the VM and remain agnostic of languages or other tooling around it. Instead, it should *enable* tooling like `sway-core` and `forc`, as those are both tools that interact with the Fuel VM in Rust.

It's easy to mistakenly leak Sway or Forc abstractions here as they are also part of the wider Fuel ecosystem that have Rust libraries. However, I think we should be careful to leave libraries and tools related to Sway and Forc to the Sway repo, and try to keep the SDK solely about exposing APIs around working with the VM in a convenient manner.

Otherwise the separation of concerns between the two repos starts to break down, and we are just going to keep introducing dependency cycles between the two repos as a result

W.r.t. this integration testing tool in particular, the existing `forc test` is basically just `cargo test`. If we do want some sort of **forc**/**sway** Rust integration testing tool, we should:

1. think about what it does that can't be done conveniently in a library that can be added in a `cargo test` and
2. likely add it to the Sway repo or some other downstream repo (and not the SDK repo).
