### ISSUE TITLE
Support multi-span errors and warnings

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#21]
Often, you want to display help text or render multiple spans in an error.

**Comment by vaivaswatha** [comment]
> A good one to start might be "not declared as mutable... but used as mutable here ^". What do you think?

Another error that might benefit from this: https://github.com/FuelLabs/sway/issues/751. "Function ^ is being redefined. It was already previously defined ^"

**Comment by anton-trunov** [comment]
One more issue that would benefit from this: #3532. The CEI pattern analysis would highlight just two lines: the one with the external call and the one with storage modification or some other effect.

**Comment by mohammadfawaz** [comment]
I recall that we tried to do this but then reverted the change for some reason? Is this too difficult to implement? I do find myself needing this often. cc @sezna. Also, if it's too complex, we should probably remove the `good first issue` tag 😄

**Comment by sezna** [comment]
There was a bug previously where the compiler would panic if the two errors were from different files, which was usually the case, so we reverted the old implementation.

**Comment by ironcev** [comment]
Here is the progress so far and two open questions to agree on. Please provide your feedback on the questions.

# Before and after :-)

![01A Constant shadowing - Before](https://github.com/FuelLabs/sway/assets/4142833/97e70a69-de62-4c86-b4a4-9e03deaf3a22)

![01B Constant shadowing - After](https://github.com/FuelLabs/sway/assets/4142833/88ddb46e-31ee-41da-98e8-006f3f71ea94)

# Open Questions
## Structure of compile messages

What do we want to support in our compile messages and how much freedom, or restriction do we want to offer. For the sake of consistency, I am for a limited, clearly defined number of elements that we can embed in a compile message. This way we can impose consistency across all our messages. So far I support these elements, and enforce them via the compile message (CM) API:

- CM can have a _label_.
- CM must have exactly one (looking for a better term) _message_ that can be an error or a warning. This is what we have as a single error/warning right now.
- CM can provide additional _info_. These are references to other places in code related to the core message. They can span over different files.
- CM can provide _help_. _Help_ is a plain text. We can provide arbitrary many _help_ strings.
- _Info_ refer to places in files, whereas the _message_ itself can (and mostly will) but does not have to (we have such situation now).

You can spot all of these elements on the above image.

What do you think of this approach? Do you see any other elements that we could need?

## Declarative API

At the moments messages are declared imperatively, pretty much like the way we do warnings right now. This means a lot of clutter and boilerplate. E,g,:

```
VariableShadowsConstant { name , constant_span} => CompileMessage {
    title: Some("Constants cannot be shadowed".to_string()),
    message: InSourceMessage::error(
          source_engine,
          self.span().clone(),
          format!("Variable \"{name}\" shadows constant with the same name.")
    ),
    in_source_info: vec![InSourceMessage::info(
         source_engine,
         constant_span.clone(),
         format!("Constant \"{name}\" is declared here.")
    )],
    help: vec![
        "Unlike variables, constants cannot be shadowed by other constants or variables, nor they can shadow variables.".to_string()
    ],
    ..Default::default()
},
```

The proposal is to define our own macros for simplifying the message definition. Something along these lines:

```
#[label("Constants cannot be shadowed")]
#[error(name.span(), "Variable \"{name}\" shadows constant with the same name.")]
#[info(constant_span, "Constant \"{name}\" is declared here.")]
#[help("Unlike variables, constants cannot be shadowed by other constants or variables, nor they can shadow variables.")]
VariableShadowsConstant { name: Ident, constant_span: Span },
```

**Comment by IGI-111** [comment]
I really like this approach. In general having a formal set of items we can use to explain a problem to the user is the right way to go.

I guess if I had to criticize this I would say that it's not very clear at a glance to the compiler dev what a "label" or an "info" is and how different they will look to the user. Ideally I'd want it to be easy to design a decent error without having to look up the spec.
Perhaps we can get close with better naming or something?

Another thing is that this:

```rust
#[label("Constants cannot be shadowed")]
#[error(name.span(), "Variable \"{name}\" shadows constant with the same name.")]
#[info(constant_span, "Constant \"{name}\" is declared here.")]
#[help("Unlike variables, constants cannot be shadowed by other constants or variables, nor they can shadow variables.")]
VariableShadowsConstant { name: Ident, constant_span: Span },
```
is probably expressed as a single proc-macro:
```rust
#[error(
    name = name.span(),
    msg = "Variable \"{name}\" shadows constant with the same name.",
    label = "Constants cannot be shadowed",
    info = (constant_span, "Constant \"{name}\" is declared here."),
    help = "Unlike variables, constants cannot be shadowed by other constants or variables, nor they can shadow variables.",
)]
VariableShadowsConstant { name: Ident, constant_span: Span },
```

One may also want to have more than a single "info", though I would expect the cases where this is necessary are rare.

**Comment by ironcev** [comment]
Completely agree that the terminology is very confusing. I wasn't happy with it either, especially when modeling the corresponding structs in code (`CompilerMessage` having field `message` of type `InSourceMessage` :scream: :scream:). But that's the first pass and you know how it is - naming things, the most difficult problem in computer science :-)

After pondering about it (a lot) and also partially inspired with the [The Anatomy of Error Messages in Rust talk](https://www.youtube.com/watch?v=oMskswu1SxM) (@IGI-111 thanks for the suggestion) I propose the following:

The whole thing is called _Diagnostic_ and has:

- _level_: Error or Warning.
- _reason_: Why is this an error/warning? Because... _Constants cannot be shadowed_. This identifies the whole family of concrete errors/warnings.
- _issue_: The issue that triggered the _diagnostic_. This is a concrete error: _Variable "y" shadows constant with the same name._
- _hints_: Additional information about the _issue_. Related lines of code, symbols, etc.
- _help_: More insights about the _issue_. Suggestions how to solve it, etc.

![01C Constant shadowing - Terminology](https://github.com/FuelLabs/sway/assets/4142833/10691746-b811-44f5-a3a7-f36969b97399)

To this, we should also add _id_ (or _code_) as suggested in #3512. It's the unique identifier of the _reason_ actually. I wouldn't call it _error code_ simply because it can be a warning code as well.

The mandatory fields are:
- _level_ 
- _id_ (once we introduce it)
- _reason_ (so far not mandatory for backward compatibility)
- _issue_

Everything else is optional. We can have arbitrary number of _hints_ spanning different files and arbitrary number of _help_ lines. 

I love the proposal of having a single proc-macro! And it doesn't mean that we cannot have several _hints_ or _help_ lines that way. E.g.:

```
#[error(
    id = "E01007",
    reason = "Constants cannot be shadowed",
    issue = (name.span(), "Constant \"{name}\" shadows imported constant with the same name."),
    hint = (constant_import_span, "Constant \"{name}\" is imported here."),
    hint = (constant_decl_span, "Constant \"{name}\" is declared here."),
    help = "Unlike variables, constants cannot be shadowed by other constants or variables, nor they can shadow variables.",
    help = "Consider renaming the constant or use an alias for the imported constant.",
)]
ConstantShadowsImportedConstant { name: Ident, constant_import_span: Span, constant_decl_span: Span },
```

**Comment by ironcev** [comment]
For the record, a very inspiring paper titled [Concepts Error Messages for Humans](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2429r0.pdf). It emphasize the importance of good (great!) error messages and provides concrete tips how to formulate them. For the purpose of this discussion, everything proposed in the paper can be achieved with the intentionally restricted number of supported elements in _Diagnostics_, listed above.

The article also mentions the [miette](https://crates.io/crates/miette) crate. Miette is an all-in-one library for defining, collecting, and rendering errors, compatible with `anyhow` and `thiserror`. Which interestingly have the `#[diagnostic]` macro similar to what we discussed:

```
#[diagnostic(
    code(oops::my::bad),
    url(docsrs),
    help("try doing it better next time?")
)]
``` 
(Yes, at glance, it looks like what we did developing our own infrastructure and combining `thiserror` and `annotate-snippets`, Miette does out of the box. But more than a glance is needed to support this claim.)

**Comment by IGI-111** [comment]
The new version looks better, I'm really looking forward to having error ids, if only because once we do we'll be able to provide `#[allow()]` style annotations.

I do think we made the right choice rolling our own error rendering if only because it gives us flexibility in how we want to tackle the problem, but miette is indeed pretty good and we could certainly take cues out of how it's designed.
