### ISSUE TITLE
EvmAddress::from leads to memory overflow error

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2217]
I originally raised this issue in the SDK channel, and even opened an issue for it (since closed).
It turns out this occurs even when not using the SDK, as discovered by @segfault-magnet .
He created a minimal repro without the SDK here: https://github.com/segfault-magnet/memory-overflow-issue/tree/42ebe730d219da50ade0f12c5994cea463ec72a3

**Comment by mohammadfawaz** [comment]
So this works fine:
```
impl EvmTest for Contract {
    fn test_function() -> EvmAddress {
        let x = 0x0000000000000000000000000000000000000000000000000000000000000000;
        ~EvmAddress::from(x)
    }
}
```
which tells me that this is the same problem as https://github.com/FuelLabs/sway/issues/1455 but a bit worse given that the above is a bad workaround.

**Comment by mohammadfawaz** [comment]
Because this is in the standard library and is critical to fix, I propose the following fix to `from()` which seems to work fine:
```rust
/// Functions for casting between the b256 and Address types.
impl From for EvmAddress {
    fn from(bits: b256) -> EvmAddress {
        // An EVM address is only 20 bytes, so the first 12 are set to zero
        let mut local_bits = bits;
        asm(r1: local_bits) {
            mcli r1 i12;
        };

        EvmAddress {
            value: local_bits,
        }
    }
}
```
In fact, the fact that we're changing `bits` in the original code is slightly incorrect because `bits` is not passed as `mut`. Changing that (once `mut` is supported for all function arguments) won't solve the problem though. The root cause of the problem is that we're trying to change a constant using `mcli`.
