### ISSUE TITLE
Default values in a `StorageMap`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2327]
We recently had a discussion around default values for storage variables defined in a `storage` block and we made a decision to enforce storage initializers for the time being because without initializers, storage variables always get initialized to 0 and that's not always the desired default behaviour. A good example of that is `Option` where the default value should be `Option::None` but `None` is not necessary encoded as zeros. 

Now, with `StorageMap`, the problem is more complicated because we can't just initialize every possible storage slots that the map can access. So, the user can just call `get(<key>)` for some `StorageMap` that has not stored anything in `<key>` yet (i.e. `insert(<key>, ..)` has not been called yet), and what they will get is zeros which may not be the desired default behavior. `StorageMap<u64, Option<u64>>` is an example of a map that would have this problem where the default values we get by calling `get()` are actually `Some(0)` which is not desirable. https://github.com/FuelLabs/sway/issues/2326 suggests that we should switch the order of `None` and `Some` so that `None` has tag 0 which would fix the issue with `Option`, but the problem can arise in other places such as use defined enums.

- Any solution that requires actually initializing the slots is going to be expensive.
- Any solution that requires keeping track of what key have been inserted into is also going to be expensive.

I don't see any other solution other than just documenting the behavior and providing tutorials/examples on how to use enums in storage maps.

We can also decide that calling `get()` before `insert()` is undefined behavior 🤷

**Comment by otrho** [comment]
> I don't see any other solution...

I think you're right.  Keeping track of whether a slot is initialised at the lowest level (like with a bloom filter) might be an option, but still would probably be too expensive and add unneeded complexity.

While the `Option` hack makes me uncomfortable, it is worth doing for this special but also common case, and we need to strongly suggest that devs always wrap their complex types in `Option`.

We *could* make `None` zero and then enforce that every value actually is `Option`, and `get()` would return `Option` too.  It would be wasteful sometimes by having the tag take up space for every inserted value, so a `b256` would have to use multiple storage slots, if my understanding of how it works is right?

I wonder then also whether we should think about reducing the size of the tag.  99% of the time it could be a byte rather than a `u64`.  But that's a different issue.

**Comment by sezna** [comment]
Packing the tag during storage would be a worthwhile optimization, as storage slot usage is much more expensive than packing/unpacking in memory.

**Comment by adlerjohn** [comment]
Relevant: https://github.com/FuelLabs/fuel-specs/issues/395

**Comment by mohammadfawaz** [comment]
Closing since we have https://github.com/FuelLabs/sway/pull/3862 now.
