### ISSUE TITLE
`main()` should not accept any arguments just yet

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2421]
This currently compiles without any diagnostics:
```rust
script;

fn main(x: u64) -> u64 {
    x
}
```
and the assembly generated doesn't make much sense.

Until https://github.com/FuelLabs/sway/issues/845 is implemented, we should probably disallow passing arguments to `main()`.

**Comment by ameer-khan-ashraf** [comment]
I would like to work on this.

**Comment by mohammadfawaz** [comment]
Thank you! Go for it and please reach out for any questions 😃

**Comment by ameer-khan-ashraf** [comment]
I have some questions. How can I contact you @mohammadfawaz ?

**Comment by mohammadfawaz** [comment]
@ameer-khan-ashraf discord is the best place to discuss this! As a starting point, one possible plate to introduce the check is right before type-checking function parameters for a function declaration: https://github.com/FuelLabs/sway/blob/376010e7b8f84334ffacd0f99e64f185c971d213/sway-core/src/semantic_analysis/ast_node/declaration/function.rs#L152
You'd have to introduce a new compile error, add the check (there is a helper call `is_main_function` somewhere I think), and emit the error if `is_main_function()` AND the number of function parameters is non-zero. You will then have to add a negative test in https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests/test_programs/should_fail

**Comment by denizsurmeli** [comment]
Hey, can I try this one if it's still open ?

**Comment by denizsurmeli** [comment]
How can we use `is_main_function()` in the `type_check`, and should we ? Rather than wrapping the `FunctionDeclaration` into `TypedAstNode` and let the `is_main_function()` unwrap it, shouldn't we just check the `name == crate::constants::DEFAULT_ENTRY_POINT_NAME`. It's effectively the same thing, but we take the longer path if we try to use `is_main_function()` I believe. Also is there a way of finding out the `TreeType` in scope of `type_check` ? I believe I should have find my way in the `ctx`.

**Comment by otrho** [comment]
I just took a quick look and I think @mohammadfawaz 's suggestion is OK but might have a couple of shortcomings (I'm sure he just looked for the most obvious starting point).  As you've pointed out the `TypedAstNode` wrapper is gone, but also it's a little deep into the process to be checking for edge cases.  If you were to put the check there we'd be checking every single function and method in the program just to see if they're `main()`.

An alternative (and again, I've only had a quick look too and this might not be the best) would be to perform the check in `semantic_analysis/program.rs` a bit like `finalize_types()` where it can just count the args to `main()`, and this could be called from `compile_ast_to_ir_to_asm()` like `finalize_types()` is.  That way it's an obvious edge case check being called from the top, rather than embedded in the type checker itself.

**Comment by denizsurmeli** [comment]
Oh okay, working on it.

**Comment by denizsurmeli** [comment]
I would love to have some comments about the implementation, if you say it's good to go I will open a PR. Thanks in advance

**Comment by otrho** [comment]
Throw up a PR anyway, it's easier for most of us to review that way. :slightly_smiling_face:
