### ISSUE TITLE
Initializing a storage slot with a `const` doesn't seem to work just yet

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2424]
I know that the const evaluator is still WIP, but this is a simple case that should probably be easy to support:
```rust
contract;

const C1 = 42;

storage {
    x: u64 = C1,
}
```
We currently get the following error:
```console
4 |
5 | storage {
6 |     x: u64 = C1,
  |              ^^ Could not evaluate initializer to a const declaration.
7 | }
  |
```

Also, the error is not great because we're not actually trying to initialize a `const` declaration here. The error should be tailored for storage initializers.

**Comment by vaivaswatha** [comment]
I had a look at this today.

Evaluation of constant declarations happen *after* type checking, somewhere just before ir-generation. So this means that the `C1` isn't yet known to be a global constant when `typed_program.get_typed_program_with_initialized_storage_slots()` is called.

I briefly tried
1. Postponing generating the initialized storage slots, but looks like this is required to generate the JSON and that tried to get it right after the type program is generated, no later.
2. Doing the constant evaluation earlier, but that wouldn't work either because it kind of relies on the sway-ir infrastructure (`Context` etc.) which isn't there at this point.
