### ISSUE TITLE
Only allow single line formatting for structure literals in `sfv2`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#2467]
Currently the line width of an item to use the `Inline` formatting (single line) is only `18usize`, and this almost never is a realistic number for inline formatting of small structures. Most of our tests are about `200-220usize` to allow formatting of structs or enums to single line. Thoughts? @kayagokalp @mitchmindtree @sezna @mohammadfawaz @emilyaherbert 

See below comments for resolved context

**Comment by mohammadfawaz** [comment]
Can you provide visual examples of what the options are? Also, what is the behaviour of `rustfmt`?

Thanks!

**Comment by kayagokalp** [comment]
One thing to note here is that with the current implementation (just like `rustfmt`), having the width of `18usize` does not necessarily mean that structures that are longer than 18 characters are going to be formatted into multiple lines. Because depending on the `max_width` provided by the config and `DEFAULT_MAX_LINE_WIDTH` it is scaled ([here](https://github.com/FuelLabs/sway/blob/master/sway-fmt-v2/src/config/heuristics.rs#L136)). 

But that being said, we want the formatter to behave as good as possible without any configuration, and without any config, it is going to basically compare the current structure length with `DEFAULT_STRUCTURE_VAR_WIDTH` (which is 18 atm). And 18 characters can be pretty short. For example, the following code piece can easily be formatted to a single line but currently, it won't (without any config)

```rust
enum Color {
 Blue: (), 
 Red: () 
}
```
This example is 32 chars long, if it is formatted to a single line

```rust
enum Color { Blue: (), Red: () }
```

So it might be a good idea to increase `DEFAULT_STRUCTURE_VAR_WIDTH`

**Comment by eureka-cpu** [comment]
@kayagokalp exactly!

**Comment by eureka-cpu** [comment]
I think one of the problems here is that we are checking the entire item line width against the maximum length of what a single _field_ should be. I'll try to address this in my expr PR as well.

**Comment by eureka-cpu** [comment]
I've found the root of the problem and the solution! We were mistakenly trying to format non-literal structs and enums as literals. So this:
```rust
pub enum Foo {
    bar: u64,
    baz: bool,
}
```
was becoming this:
```rust
pub enum Foo { bar: u64, baz: bool }
```
when really what we want is only for _literals_ to be formatted this way:
```rust
let foo = Foo { bar: 0, baz: true };
```

I will fix this in `expr` since it is relevant to that PR
