### ISSUE TITLE
Discuss alternate ways to provide config-time constants to programs

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#2575]
Currently, config-time constants are declared in the toml file as constant expressions. While this is a good start, we should also allow constants to be injected from perhaps build flags provided to `forc`, or from the SDK in other ways.

#2549 introduces a mechanism for injecting constant expressions into the program before compilation begins via the toml file. This issue does not involve any more compiler work, rather, just adding alternate methods to either `forc` or the SDK to provide these constants to the compilation process.

**Comment by otrho** [comment]
There are 3 general ways of configuring programs, yeah?
- [ ] CLI args.
- [x] config file.
- [ ] the environment (variables).

**Comment by mitchmindtree** [comment]
Hey @sezna, just found this issue!

I'll leave my thoughts here from our discussion for prosperity as it seems the best place:

## Goals

It seems we have identified two major use-cases for "configuration time" constants:

1. **Automatically pass through addresses from pre-deployed contracts**. Often application developers will have multiple contracts that they wish to deploy in a particular order based on their inter-dependency.
2. **Changing between sets of long-term-use constants.** It can be useful for application developers to be able to switch between multiple sets of compile-time constants e.g. based on the network they wish to target. These might include things like network-specific values for representing contracts, asset IDs, block value / delay durations, and so on.

## Proposal

### Part 1. Workspaces #1777

Support for multi-package "workspace"s is on the Tooling team's next milestone. As a part of this work, one of the primary goals is to enable this automated propagation of contract addresses to dependent projects.

For non-workspace contract address dependencies, we can consider coming up with some sort of deployment metadata archival standard for Forc projects (perhaps similar to @nfurfaro's `deployments` directory suggestion here: https://github.com/FuelLabs/sway/issues/577#issuecomment-1071042772). However, implementation might be easiest if we can start with first handling workspace-local contracts before moving on to remove contracts (e.g. hosted under separate git repositories/workspaces).

#1777 still needs a design, but we can imagine having another table that looks a lot like `[dependencies]`, but that is used to specify *deployment* dependencies rather than solely *build* dependencies.

### Part 2. Conditional compilation (no main issue, #2552 related)

For sets of constants that differ based on e.g. test networks or target contracts, I propose we provide something similar to Rust's conditional compilation feature. E.g. users could specify sets of constants with something like the following:

*config_test.sw*
```rust
const DURATION = 10;
const ASSET_ID = 0x1324...;
const CONTRACT_ID = 0x5678...;
```
*config_release.sw*
```rust
const DURATION = 1000;
const ASSET_ID = 0x8149...;
const CONTRACT_ID = 0x9852...;
```
*main.sw*
```rust
#[profile(test)]
dep config_test as config;
#[profile(release)]
dep config_release as config;

fn foo() {
    // Do stuff with `config::DURATION`, `config::ASSET_ID`, `config::CONTRACT_ID`
}
```

This is similar to how cross-platform Rust projects (like [winit](https://github.com/rust-windowing/winit) or [cpal](https://github.com/RustAudio/cpal)) handle providing different constants (and functions or other items) based on the target platform or OS, which is perhaps not dissimilar to having different deployment networks, etc.

The `profile` attribute used above is a placeholder, but one could imagine replacing this with something like rust's `feature` attribute to allow users to select which profile they want at build time e.g. `forc deploy --profile "release"`, `forc deploy --feature "foo-testnet"`.

This approach provides the benefit of allowing users to write normal Sway code to declare their constant values, and also opens the possibility of not just switching between constant values, but functions and other items too.

### Compile-time Environment Variable inspection

@sezna also made a great point (as did @otrho above) that supporting something similar to Rust's `env!` macro would also give users a lot of flexibility w.r.t. how they handle compile-time constants. This could potentially address alternative use-cases not covered by the above.

## Concerns with using `Forc.toml`

My primary concerns w.r.t. using `Forc.toml` are:

1. These values will change frequently (part of the reason why we want some new feature and not use `const`s directly). Having these values declared in the `Forc.toml` will lead to a lot of git noise and potential conflicts in forc projects.
2. Unnecessarily requires translating `toml` strings to valid Sway code. Declaring Sway constant values is likely better achieved in Sway code, especially if we imagine users wanting to declare more sophisticated nested struct or enum values.
3. Currently, the approach doesn't really solve either of our two use-cases.
    - For use-case 1, users are still required to frequently update these values manually. The only difference is that now they're doing so in the forc manifest rather than a Sway `const` directly. By giving `forc` greater awareness of its contract inputs (as in proposal Pt. 1), we can remove the need to manually define these contract addresses altogether, and can avoid the diff noise that would otherwise occur.
    - For use-case 2, these values will frequently need to be changed back and forth, e.g. based on the target network. This would not be necessary under the conditional compilation approach mentioned above (proposal Pt. 2).

## Concerns with Deploy scripts

Occasionally, the idea of deploy scripts gets mentioned as a potential approach to providing more flexibility around deployment. I opened a discussion with some concerns around deploy scripts a little while ago [here](https://github.com/FuelLabs/sway/discussions/2435), but it seems github discussions might not show up in notifications :smiling_face_with_tear: 

---

Also cc @adlerjohn @nfurfaro @simonr0204 as this is related to the slack chat around "config-time" constants.

**Comment by JoshuaBatty** [comment]
I'm personally all in favor of this approach for the same vaild reasons you raised above @mitchmindtree. + 1 from me.

**Comment by mohammadfawaz** [comment]
Closing in favor of the approach described in https://github.com/FuelLabs/sway-rfcs/pull/19
