### ISSUE TITLE
Immediate18TooLarge still appears when running certain tests

### ISSUE THREAD

**Issue by ewynx** [FuelLabs/sway#2674]
Usign forc `0.21.0` and fuel-core `0.9.8`, we've been able to run more tests than before but still run into the `Immediate18TooLarge` error. 

Example of when it pops up: run `forc test` in `tests_bls12_381` for the code as it is in [this commit ](https://github.com/hashcloak/fuel-crypto/commit/f37ba7f2c7371e5cc861430653820115752bf81f). 

Context: This runs add, sub, mul & square for Fp. Before the improvements testing square by itself would run into that same error. After the improvements, testing square by itself works, but the combination of these tests won't run.

**Comment by otrho** [comment]
I took a look at this just now, checking out that branch and commit and running `forc` v0.21.0 (without running `fuel-core` at all though) and it just blew up.  Used all memory and was killed.

So something bad is going on here, I'll keep digging, though I didn't even get to the `Immedate18TooLarge` problem.

**Comment by otrho** [comment]
OK, not surprisingly, this issue is about trying to emit a `jnzi` instruction which wants to jump to an address outside of the 1MB range that an 18bit immediate (256K * 4) can represent.  This is happening currently during register allocation.

The solution is to use the new `jne` instruction instead (or to introduce relative jumps to the VM, which might happen one day).  The problem with implementing this is we need to put a constant into a register first, so a single jump instruction becomes two new instructions, `load` and `jne`.

This will need to be done before/while we 'realise' the organisational ops from symbolic labels to absolute offsets, a.k.a. address resolution.  And from then on, we need to be careful when dealing with these pairs that they continue to be treated as such -- essentially single jump instructions.

This isn't _too_ hard, except right now I'm in the midst of refactoring  a lot of the codegen, particularly regarding the order we do register allocation and address resolution, and so I think any effort to fix this issue needs to wait until that's done.

There's a bit of a chicken and egg situation going on too, I think.  If we need to use a register for `jne` then it should be nominated before we do register allocation.  But we don't know that a jump is nonviable until we get to address resolution.  Address resolution will be done after register allocation though, post- the new codegen refactor.  Right now I'm thinking that we may need to reserve a register specifically for use with `jmp` and `jne` so that register allocation can ignore it and we don't clobber anything else.

**Comment by otrho** [comment]
That would work after I switch the order of allocation and address resolution, without needing `NOP` replacements. The work I'm doing now will adjust the allocator to work with 'organisational' ops, where we still jump to labels, in which case the jump is still either immediate or constant-dynamic and metadata isn't needed.  And in that case I think it'll be worthwhile just reserving a register for dynamic jumps so the allocator doesn't have to worry about it.

**Comment by adlerjohn** [comment]
Reserving a register or two seems fine, since there are so many of them.

**Comment by otrho** [comment]
> Reserving a register or two seems fine, since there are so many of them.

I've already started to in my calls branch - `$tmp`...

**Comment by otrho** [comment]
I think this may be resolved now, if temporarily, with the recent improvements to codegen.  The code is a little stale and the test doesn't compile, though the Sway does.  I think.

**Comment by otrho** [comment]
It should definitely be fixed by https://github.com/FuelLabs/sway/pull/3109 too.

**Comment by mohammadfawaz** [comment]
Closing now that https://github.com/FuelLabs/sway/pull/3109 is merged. Thanks @otrho!
