### ISSUE TITLE
`swayfmt` needs an issue template

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#2725]
Bugs:
- `forc` version (run the command `forc --version`)
  - `rust` version (run the command `rustc --version`)
  - operating system and version
  - copy and paste the following into separate and labeled code blocks:
    - error output, if any
    - the full code snippet the problem originated from
    - the current output after formatting
    - the desired output after formatting
  - optionally, a solution to the problem
Features:
  - a detailed description of the feature
  - an example of what the code looks like before being formatted and what the code would look like after formatting

**Comment by bingcicle** [comment]
I think we really only the below info:

1) the repro of the code that fails to format,
2) output of `forc fmt` when executed on the file above.
3) what you expect the formatter to do
4) forc-fmt version

Step 2 is important - browsing through the issues there's some that contain just a block of code that isn't formattable immediately, and sometimes it seems like we might have to guess at what the person who raised the issue wants. Enforcing that people post the output of `forc fmt` makes it so that at the very least the code sample is a runnable piece of code that we can copy paste for immediate repro.

Does the version of rust matter for the formatter?

**Comment by eureka-cpu** [comment]
In general issue templates would be good to have for the repo as a whole, and this is just one piece of that puzzle.
