### ISSUE TITLE
bug: ICE on a reverting transaction in the SDK tests

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/sway#2822]
I get this error: 

```
fuels-rs/packages/fuels/tests/test_projects/revert_transaction_error$ forc build
  Creating a new `Forc.lock` file. (Cause: lock file did not exist)
    Adding core
    Adding std git+https://github.com/fuellabs/sway?tag=v0.24.4#f7800e18979dd8e4c8d672b8e7aae1758c2edb88
   Created new lock file at fuels-rs/packages/fuels/tests/test_projects/revert_transaction_error/Forc.lock
  Compiled library "core".
  Compiled library "std".
  
error
 |
0 | unknown source location
 | ^^^^^^^^^^^^^^^^^^^^^^^ Internal compiler error: UnknownType { span: Span { src (ptr): 0x55eac6066890, path: None, start: 0, end: 23, as_str(): "unknown source location" } }
Please file an issue on the repository and include the code that triggered this error.
 |
____

  Aborting due to 1 error.
Error: Failed to compile revert_transaction_error
```

This error happens with both `forc 0.24.3` and `forc 0.24.4`.
It does *not* happen on `forc 0.23.0` ! :smiley_cat: 
I have `rustc 1.63.0` and `fuels-rs 0.24`.

**Comment by mohammadfawaz** [comment]
Small reproducer:
```rust
script;

fn main() {
    asm(r1: 0) {
        rvrt r1;
    };
}
```
If I remove the semicolon after the `asm` block, the script compiles.

**Comment by iqdecay** [comment]
Cannot reproduce my original bug on `forc 0.24.5`

**Comment by emilyaherbert** [comment]
Here is where we are calculating if the asm block diverges:
https://github.com/FuelLabs/sway/blob/0d0c265e6ca6c56126d331ea469cfbe8bb5e0370/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L1214

The issue is in that, from a typing perspective, it's not enough just to know if the asm block diverges---the way in which it diverges changes its return type (e.g. a revert should have different typing rules than a return, as seen in this example). I propose that in the short term we change the above LOC to exclude `"rvrt"`. It seems that all asm blocks have the unit type anyway, so we could change it to something like this:

```rust
        let is_return = asm
            .body
            .iter()
            .any(|asm_op| matches!(asm_op.op_name.as_str(), "ret"));
        let return_type = if is_return {
            insert_type(TypeInfo::Unknown)
        } else {
            check!(
                ctx.resolve_type_with_self(
                    insert_type(asm.return_type.clone()),
                    &asm_span,
                    EnforceTypeArguments::No,
                    None
                ),
                insert_type(TypeInfo::ErrorRecovery),
                warnings,
                errors,
            )
        };
```

This should be enough to change all of the instances of asm blocks with `rvrt` to be `TypeInfo::Tuple(vec!())`, meaning they will type soundly regardless of if there is a semicolon or not. In the long term as our needs grow, we may want to consider a more robust solution, like adding something like `TypeInfo::Revert` or `TypeInfo::Never` to the type system. Rust has a never type on nightly: https://doc.rust-lang.org/std/primitive.never.html

I also propose that we create an issue to fix how we use this function in particular cases:
https://github.com/FuelLabs/sway/blob/0d0c265e6ca6c56126d331ea469cfbe8bb5e0370/sway-core/src/type_system/type_engine.rs#L764

we should change what is passed to the `error_span` argument to prevent the `unknown source location` message. For example, in the case of asm blocks, the `error_span` could be either the particular `rvrt` or `ret`, or the whole block, or just the signature, etc.

**Comment by mohammadfawaz** [comment]
> It seems that all asm blocks have the unit type anyway

`asm` blocks may have a different type if they actually return something (like the asm block for `add` for example). But regardless, I agree with your proposed solution above. I will put up a PR shortly.

**Comment by emilyaherbert** [comment]
> asm blocks may have a different type if they actually return something (like the asm block for add for example)

**Comment by emilyaherbert** [comment]
> asm blocks may have a different type if they actually return something (like the asm block for add for example)

Ah yeah, for some clarification, I meant that at the time that type checking hits this LOC: https://github.com/FuelLabs/sway/blob/0d0c265e6ca6c56126d331ea469cfbe8bb5e0370/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L1214

It seems that the (untyped) `asm.return_type` is `TypeInfo::Tuple(vec!())`.
