### ISSUE TITLE
LSP Hover: Support go_to button links in the hover box

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#2852]
eg 

<img width="471" alt="Screen Shot 2022-09-26 at 2 23 20 pm" src="https://user-images.githubusercontent.com/1289413/192193438-3a3dcb58-a2ab-42f1-aa02-ba2e53d90d70.png">

**Comment by sdankel** [comment]
Since this is not yet part of the LSP spec, we'd need to return an additional field in the `hover` response.

With tower-lsp, there seems to be no way to override the method signature that they define. Opened an issue: https://github.com/ebkalderon/tower-lsp/issues/393

We'll either need this to be supported in tower-lsp or move to another framework to be able to do this feature.

**Comment by sdankel** [comment]
Actually, never mind. We can just add the links in the markdown and it looks fine. 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/47993817/234438883-d9344edf-23ae-4c3e-9c09-f5cf551623f3.png">

I was looking at how rust-analyzer does it, which involves implementing the hover provider on the client side to handle the extra `actions` argument from the `hover` response, but I don't see why that's necessary.

**Comment by sdankel** [comment]
New problem I'm running into: https://github.com/microsoft/vscode/issues/180913
