### ISSUE TITLE
Rename `std::math::Exponentiate` trait

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2857]
Perhaps rename this trait to `Exponent` to avoid the use of a verb for a trait name.

**Comment by nfurfaro** [comment]
There is now also a `trait Exponent` in `std::math`, which could be confusing.
Perhaps we rename this one to `Pow` or `Power` ? i.e:
```
pub trait Power {
    fn pow(self, exponent: Self) -> Self;
}
```
cc @otrho @mohammadfawaz

**Comment by otrho** [comment]
So IMO yes, `Power` is better than `Exponentiate` due to `pow()`, and we keep `Exponent` and `exp()`.

In old school maths libraries `exp` uses a base of _e_ and `pow` supplies the base, and this would be what we're doing there in `math.h`.

Interestingly Rust doesn't have a trait for `pow()` or `exp()`, I guess because there's no operator overriding involved.

**Comment by Braqzen** [comment]
Isn't this `breaking` too?

**Comment by mohammadfawaz** [comment]
> Isn't this `breaking` too?

That is indeed breaking.
