### ISSUE TITLE
Document `if let` in the Sway Book

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2939]
A few things I've noticed to be missing or out of date from the docs:
- I can't find any mention of the `if let` syntax in the docs

**Comment by nfurfaro** [comment]
@mohammadfawaz I updated my description as I wasn't on the latest Sway book version. I naievely thought that refreshing the browser would load the latest version, but I was waaay back on 16.x :)

**Comment by mohammadfawaz** [comment]
@mohammadfawaz I updated my description as I wasn't on the latest Sway book version. I naively thought that refreshing the browser would load the latest version, but I was waaay back on 16.x :)

Interestingly, @mauricewbr told me that he faced the same issue actually. We do need to fix this so that `latest` stays in the web address and doesn't get resolved to a fixed version.
