### ISSUE TITLE
Fix the error message for incorrect number of arguments on method calls

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#2949]
This Sway code:

```rust
script;

struct Data {
    value: u64
}

impl Data {
    fn add_values(self, other: Data) -> u64 {
        self.value + other.value
    }
}

fn main() -> u64 {
    let data1 = Data { 
        value: 42u64
    };
    let data2 = Data {
        value: 1u64
    };
    data1.add_values()
}
```

gives this error message:

```bash
   |
18 | 
19 |     };
20 |     data1.add_values()
   |           ^^^^^^^^^^ Function "add_values" expects 2 arguments but you provided 1.
21 | }
   |
____

  Aborting due to 1 error.
```

When it should say "expects 1 argument".

**Comment by mohammadfawaz** [comment]
> When it should say "expects 1 argument".

Ugh yeah that's because `add_values()` is a method that requires `self`. The error message is accounting for `self` here as 1 argument. We should:
- Emit the error message above if `add_values()` is used as an associated function: `Data::add_values(data1)`
- Emit the error message you're proposing if `add_values()` is used using the `.` syntax.
