### ISSUE TITLE
Using `!` in a diverging expression not working in #2909

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3061]
#2909 simply changes `fn not()` in `core::ops` to become a trait `Not` that is implemented for `bool` and all integer types. For some reason, this broke `should_pass/language/diverging_exprs`. Specifically, the following test case:
```rust
script;

fn diverge_in_op_not() -> u64 {
    let b: bool = ! {
        return 5;
    };
    123
}

fn main() {
    diverge_in_op_not();
}
```
Error:
```console
163 | fn diverge_in_op_not() -> u64 {
164 |     let b: bool = ! {
    |                   ^ No method named "not" found for type "unknown".
165 |         return 5;
166 |     };
```
It's what the problem is yet, but I will disable the test (as it is not that important of a use case) and track fixing it in this issue.

**Comment by mohammadfawaz** [comment]
@emilyaherbert what are you thoughts on this? For some background:

* Previously, the `not()` function was a free function and not a method. So it just takes a `bool` and returns ` bool`. The parser used to de-sugar `!exp` to `core::ops::not(exp)`. In the example above, because `not()` is known to take a bool, the type of `{ return 5; }` becomes `bool`. It starts as `Unknown` but then is casted to `bool` due to the signature of `not()`. and things just worked.
* After https://github.com/FuelLabs/sway/pull/2909, `not()` became a method which takes `Self` and returns `Self` because we can now use it for integers. So, `! { return 5; }` now de-sugars to `{ return 5; }.not()`. From this alone, there is now way for us to know what the type of `{ return 5; } should be, but if we look further, then `let b: bool =` tells us the type. Is our type system advanced enough to see beyond a the method application? That is, is the issue here a bug or is it a known missing feature?

**Comment by emilyaherbert** [comment]
This is probably failing because of how diverging expressions are typed when they are in the "`self`" position in a method call. When the compiler encounters a method call, it performs a lookup using the type of the argument in the `self` position and the name of the method. If that type is `TypeInfo::Unknown`, there will be no methods to be found, because there are no methods implemented for the unknown type. To that end, we should probably have the compiler return an ICE in the case of a method lookup on an unknown type.

But even without considering the method call, the fact that the code block `{ return 5; }` is typing to `TypeInfo::Unknown` is a bug---we should be able to type it to `TypeInfo::Numeric`. It looks like this `TypeInfo::Unknown` is being generated here: https://github.com/FuelLabs/sway/blob/ef8088ab8282a14579bde6af7fec9314435b4a9d/sway-core/src/semantic_analysis/ast_node/code_block.rs#L40

There is already some infrastructure for typing nested return statements inside of `ty::TyFunctionDeclaration::type_check`: https://github.com/FuelLabs/sway/blob/ef8088ab8282a14579bde6af7fec9314435b4a9d/sway-core/src/semantic_analysis/ast_node/declaration/function.rs#L110

I recommend that we try moving this functionality to `ty::TyCodeBlock::type_check` so that we can type `{ return 5; }` before doing a lookup of the method call.

**Comment by mohammadfawaz** [comment]
So the type of `{ return 5; }` is effectively `Never` which we've been using `Unknown` for as a replacement. I think the idea is that the `u64` type here matches the return type of the function but the type of the `{ return 5; }` expression itself is not `u64`. It should coerce to whatever type the current context enforces. So, in
```rust
fn diverge_in_op_not() -> u64 {
    let b: bool = ! {
        return 5;
    };
    123
}
```
the type of `{ return 5; }` should be `bool`. The code now breaks because `not()` part of a trait with no specified type but previously it was a free function that takes only `bool`.

**Comment by mohammadfawaz** [comment]
Assigning to @emilyaherbert because I can't assign to @esdrubal
