### ISSUE TITLE
`forc run` - allow for specifying `main` arguments for scripts

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3439]
Currently, using `forc run` there is no way to provide main arguments for scripts.

## CLI arguments

We couild *at least* allow for specifying primitive arguments via the command line, e.g. 

```console
forc run -- arg1 arg2 arg3
```

## `script-args.json` or similar?

We could also settle on a file format (toml or json) that provides both the argument values and their types so that the user can update their file and do something like `forc run --args script-args.json` or similar.

We might need to support some sort of args file like this either way if we want to allow users to submit more sophisticated types via main arguments. Perhaps we can extract the `fuels` representation into `fuels-types` (if it isn't already) so that we can re-use the same serializable main args format directly.

This is not a big priority for users already using the Rust or TS SDKs directly to run scripts, but a feature like this would be especially useful for users with simpler scripts, or whose Sway projects are embedded in other languages.

cc @nfurfaro @simonr0204 let us know if you have any more thoughts / ideas on this!

**Comment by bingcicle** [comment]
Going to look into picking this up. Are there any updates/changes in the requirements I should know of? cc @nfurfaro @simonr0204

**Comment by nfurfaro** [comment]
@bingcicle I would be interested in picking this up if you wanted to focus more on the package registry stuff? No worries if you want to keep going with it though.

**Comment by bingcicle** [comment]
@nfurfaro Yes, for sure! I'll unassign myself and assign you instead :+1:

**Comment by kayagokalp** [comment]
Started looking into this, seems like we already depend on the SDK and SDK handles this pretty nice, so maybe we should remove the tx creation implementation in forc run and make forc run a cli wrapper around the SDK's script functionality. Any thoughts?

**Comment by kayagokalp** [comment]
Also to add more context, this was not possible to be done in a safe way since we need a `WalletUnlocked` instance to be created by the user's input in the CLI. But since we have forc-wallet as a lib now, we can get the `WalletUnlocked` safely from the user's vault, and sign operation can be done automatically. This enable us to use SDK's already established workflow.

1. Build the project obtain the artifacts.
2. Create a provider using `node_url` passed by the user.
3.  If user specified `--unsigned`, create a dummy/default wallet. Otherwise call forc-wallet as a lib, and obtain a `WalletUnlocked` safely.
4. With the obtained `WalletUnlocked` (which is created by using the provider and forc-wallet invocation/default wallet) call the main function of the script like in the [example](https://rust.fuel.network/v0.41.0/getting-started/running-scripts.html?highlight=Scripts#running-scripts) of SDK
