### ISSUE TITLE
When checking for a parent workspace manifest, `forc` gives a confusing error if it fails to parse a parent manifest as a workspace

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3535]
Raised by @segfault-magnet in slack:

> Hey team. Not sure whether to write here or in tooling. If I build a sway project located in /home/some_user/some_folder/some_folder_2/the_project it will fail if there is a Forc.toml in any of the parent directories. All my sway builds started failing due to the existence of ~/Forc.toml. If I remove it the builds pass again. The errors were something like:
> 
> Error: failed to parse manifest:"...,
> Error: failed to parse manifest: missing field `members` at line 7 column 1.

We should either:

1. Provide a much more concise explanation of the error or
2. Warn that a parent `Cargo.toml` was detected that was not a valid workspace or
3. Silently ignore parent manifests that are _not_ workspaces with a members set containing the current package.

We should investigate cargo's behaviour here, it appears to have changed recently as previously cargo used to provide a warning in this situation (option 2), whereas currently it appears to silently ignore (option 3).

**Comment by kayagokalp** [comment]
I am leaning towards the second option since it is not clear how we can make sure that 3rd option also does not silence `Forc.toml`'s declaring a workspace but have some problems from random `Forc.toml` residing in a parent dir.  If we go with option 3, I think we should give warnings and erros for `Forc.toml` that actually tries to declare a workspace but be silent about other ones. A possible way for this differentiation is not clear to me at the moment. But option 1/2 seems quite straightforward.

**Comment by mitchmindtree** [comment]
Yeah I think in the long run we likely want to support `3.` giving a useful error in the case that we find a `Forc.toml` with `[workspace]` but is incorrectly formatted etc as you mentioned. I'd be content with either 1. or 2. in the meantime as a temporary patch.
