### ISSUE TITLE
Internal compiler error: Store must be to a pointer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#3570]
Version: `forc 0.31.1`

```rust
contract;

abi MyContract {
    fn test_function(mut amount: u64) -> bool;
}

impl MyContract for Contract {
    fn test_function(mut amount: u64) -> bool {
        if true {
            // Required to cause ICE
            amount = 1;
        }
        true
    }
}
```

**Comment by vaivaswatha** [comment]
Tthe issue seems to be that it specifies `mut amount: u64` instead of `ref mut amount: u64`. 
For the latter, a proper error "Ref mutable parameter is not supported for contract ABI function" is thrown.

For non-ABI functions, if we have just `mut amount: u64`, we do get a good error "This parameter was declared as mutable, which is not supported yet, did you mean to use ref mut?". So that check just needs to be done for ABI methods as well.

**Comment by vaivaswatha** [comment]
Related: https://github.com/FuelLabs/sway/issues/2719/
