### ISSUE TITLE
Add a way to omit tests at parsing step

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#3622]
Currently tests are parsed and type checked even if we have tests disabled. This is both unnecessary and also blocks me on #3262.

**Comment by mitchmindtree** [comment]
> This is both unnecessary and also blocks me on https://github.com/FuelLabs/sway/issues/3262.

Just to clarify: Currently, when tests are not enabled, we still include them during type checking, but omit them from IR. This is intentional, to ensure that the tests functions are available to DCA to avoid producing unnecessary warnings about dead code in the case that some items are only used within the test functions.

That said, as we need the contract's ID in order to build the contract's unit tests (seeing as we wish to call into that contract), we cannot type-check unit tests on the first build that produces the contract's ID. As discussed on slack, adding a flag to sway-core's BuildConfig like `omit_tests_from_parsed` or similar could be the way to go here, but we'll need to silence the aforementioned unnecessary dead code warnings on this contract ID build.

**Comment by mohammadfawaz** [comment]
> Just to clarify: Currently, when tests are not enabled, we still include them during type checking, but omit them from IR. This is intentional, to ensure that the tests functions are available to DCA to avoid producing unnecessary warnings about dead code in the case that some items are only used within the test functions.

[This](https://github.com/FuelLabs/sway/issues/3586) is somewhat related. There are some DCA warnings are get generated today from just running `forc build` even though they have nothing to do with the actual non-test code being built. Is this expected behavior? Shouldn't we not care about the tests unless we're running `forc test`? To your point, it's important that types that are only used in tests do not cause a DCA warning but also DCA warnings that are generated from _inside_ tests (such as unused return value) should not be emitted when running `forc build`.

**Comment by mitchmindtree** [comment]
Ahhhh originally, I thought Rust was also type-checking tests (regardless of `#[test]`), but after double checking Rust's behaviour it seems they only *parse* the tests unless `cargo build --tests` or `cargo test` is run, which makes sense in retrospect!

@mohammadfawaz I think you're right in that we should likely stop including tests during type-checking and DCA in general (unless running `forc test` or `forc build --tests`).Perhaps we _can_ make this a more general change to the way tests are included in compilation.

One nicety that we're missing that Rust provides in aid of testing and avoiding lots of dead-code warnings is conditional compilation, i.e. `#[cfg(test)]`. E.g. a user can decorate an item or module with `#[cfg(test)]` and know that it won't interfere with the regular, non-test compilation.

I wonder if we should be focused on landing `#[cfg()]` support first, as it is more of a general solution to the problem we're trying to solve here? Then perhaps we could additionally "desugar" each appearance of `#[test]` to `#[cfg(test)]` which would take care of this issue for us?

I might have a go at writing up a short proposal for `#[cfg()]` either under #2552 or a more general issue. I think the lessons we've learned in supporting `#[test]` might make this an easier solve than we previously thought?
