### ISSUE TITLE
`forc build` does not build all workspace members if two members share the same name

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3650]
When running `forc build` and using a workspace, if members have the same name in their local Forc.toml file, both will not compile. 

In the following example this is the project structure:

```
test_project/
├──  member1/
|     └── src/
|     |     └── main.sw
|     └── Forc.toml
├── member2/
|     └── src/
|     |     └── main.sw
|     └── Forc.toml
└── Forc.toml
```

This is the parent directory Forc.toml file: 

```rust
[workspace]
members = [
  "./member1",
  "./member2",
]
```

Both members of the workspace have the following identical local Forc.toml file:

```rust
[project]
authors = ["Cam Fuel"]
entry = "main.sw"
license = "Apache-2.0"
name = "member"

[dependencies]
```

Despite both being listed as separate members in the workspace, because they have the same name in the local Forc.toml file only one will compile. 

Tested with forc v0.32.2

**Comment by kayagokalp** [comment]
Hmm, I wonder if this is something that we should allow or provide an error for. What do you think @mitchmindtree?

**Comment by mitchmindtree** [comment]
I'm not sure off the top of my head where the second member would get lost here. My guess is that somewhere we're only using the package name `String` as a key (e.g. within a Map or a Set), when we should possibly be using the whole `Pkg` type (which includes both the `name` and `source` fields). By using `Pkg`, we could allow for multiple members with the same name.

Whether or not that's something we want to allow is questionable I guess. A simple path forward might be to check if cargo allows this, and follow suit?

Whether or not we want to provide an error, we'll need to first identify where we're losing the package with duplicate name first.

**Comment by kayagokalp** [comment]
it seems like cargo does not allow this:

I created two workspace members named "test_lib" and "test_lib2" which both had "test_lib" as package names in their `Cargo.toml`s just like the setup in the issue here. Trying to build them:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/20915464/213689886-c10ba26d-4ba1-45fe-841e-ad84eaaf3e1e.png">

I guess it makes sense to error out, I am planning to add a validity check for this to the build plan but will take a closer look shortly.
