### ISSUE TITLE
LSP Crashing with ` Char index out of bounds`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3699]
Refer to the forum discussion in https://forum.fuel.network/t/the-sway-language-server-server-crashed-5-times-in-the-last-3-minutes/1188

**Comment by kayagokalp** [comment]
I feel like this might be somehow related to the formatter too since the error seems to be happening once you format the code 5 times (if i understood the last sentence in the post correctly).

The weird thing is if this is happening after formatting the formatted code, this should have been caught by our tests because we have a stability test that does exactly that (format the formatted code and try to see if anything changes). Anyways i will add the relevant tag if this is indeed formatter related after some digging.

**Comment by sdankel** [comment]
@alexey I was unable to repro this. Is this still happening for you?
