### ISSUE TITLE
LSP missing tokens: intrinsics

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#3714]
Unable to access span information for functions with “hidden” naming convention (e.g. `__revert`)

![image](https://user-images.githubusercontent.com/47993817/211123635-4c26d051-2c66-4c16-af7e-c12c87a36900.png)

**Comment by JoshuaBatty** [comment]
would be nice to have syntax highlighting for these somewhere between a keyword and a regular function call.

**Comment by mohammadfawaz** [comment]
A list of all available ones can be found in https://github.com/FuelLabs/sway/blob/master/sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs. They're also all documented in https://fuellabs.github.io/sway/v0.33.0/book/reference/compiler_intrinsics.html (except for `__get_storage_key` because that's going away once we have storage references)

**Comment by JoshuaBatty** [comment]
Amazing, thanks @mohammadfawaz!
