### ISSUE TITLE
Type inference fails for nested types

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/sway#3741]
Some tests in the Rust SDK fail to compile with the release of forc 0.33.0

Here is a minimal example:

```rust
fn main() -> bool {
   let mut exp_vec_in_a_vec_in_a_struct_in_a_vec = Vec::new();

   let mut inner_vec_1 = Vec::new();

   let inner_inner_vec_1 = vec_from([0, 1, 2]);
   inner_vec_1.push(inner_inner_vec_1);

   exp_vec_in_a_vec_in_a_struct_in_a_vec.push(SomeStruct { a: inner_vec_1 });

   true
}
```

Which leads to:
```
inner_vec_1 : This parameter was declared as type Vec<u32>, but argument of type SomeStruct<Vec<Vec<u32>>> was provided.
```

The example complies without issues if we manually set the type of `exp_vec_in_a_vec_in_a_struct_in_a_vec` to `Vec<SomeStruct<Vec<Vec<u32>>>>`

**Comment by esdrubal** [comment]
Hi MujkicA, thank you for reporting the issue.

I came up with this minimal test case.
```rust
script;

struct SomeStruct<T> {
    a: T,
}

fn main() -> bool {
    let mut vec1 = Vec::new();
    let mut vec2 = Vec::new();

    vec2.push(54u32);
    vec1.push(SomeStruct { a: 42 });

    true
}
```
```
11 |     vec2.push(54u32);
12 |     vec1.push(SomeStruct { a: 42 });
   |               ^^^^^^^^^^^^^^^^^^^^ This parameter was declared as type u32, but argument of type SomeStruct<u64> was provided.
```

Also did a git bisect and found out that the regression was introduced in: 34cbc5a6ede72e367a3fead812631a64ae2f765c
@emilyaherbert any idea how to fix this?

**Comment by emilyaherbert** [comment]
Oh my, this is critical!

The message "This parameter was declared as type u32, but argument of type SomeStruct<u64> was provided." Is given when the `TraitMap` finds a method for a type, then that method has an incorrectly unified the `self` type. In this case, this is probably happening because the Placeholder types in `vec2` are being unified from `vec1.push`.

My first approach towards fixing it would be to replace the Placeholder types in the methods of `vec2` with new `TypeId`s so that type unification from `vec1.push` doesn't effect `vec2`.
