### ISSUE TITLE
Add a flag to forc to reverse the order of printed errors

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#3860]
Requested by @nfurfaro in a recent sway sync. Since most of the time, lots of errors propagates from the first error (meaning that once the first error is fixed, all of them goes away) it would make sense to be able to revert the order so that users do not need to scroll.

**Comment by nfurfaro** [comment]
Thinking about this a bit more, I think the first thing to check is that given libraries `b`, `c` & `d` which all depend on library `a`, if there's a compile error in `a`, forc should not attempt to build the dependent libs. This would go a long way to resolving my issue and deals with the root more directly.

**Comment by otrho** [comment]
This is a bit of a tricky UI question.  Compilers historically have tried to continue and gather errors greedily to try and improve the edit-compile-run loop, by not insisting that each error must be fixed one at a time.  This is especially important for long compile times on big projects.  Just because `a` has an error doesn't mean `b` will have a problem, or that `b`'s error is related.  OTOH pages of cascading errors due to a single typo is a pain in the neck.

Reversing the order of the errors is an interesting idea though -- I don't think I've ever seen it before (at least outside of an IDE).  Not needing to scroll to see the first error would be useful.

**Comment by nfurfaro** [comment]
Honestly, it would save a bunch of time spent trying to find the top of the most recent errors, as the first one is alway the one I want to fix .

**Comment by gr00vytvniks** [comment]
This seems like a challenge I'm willing to take on if nobody else has been assigned

**Comment by gr00vytvniks** [comment]
I'm having trouble finding where we emit errors. Is this an issue with `forc` or `forc-pkg`, or is it somewhere else in the Sway repo?

**Comment by kayagokalp** [comment]
@gr00vytvniks 

Hmm, I would look into places like:

https://github.com/FuelLabs/sway/blob/1d31ff6c854cbf7533f151b74fd4acdd937b0682/forc-pkg/src/pkg.rs#L2567-L2570

Which seems to use `print_on_failure` from `forc-util` which can be seen below:

https://github.com/FuelLabs/sway/blob/1d31ff6c854cbf7533f151b74fd4acdd937b0682/forc-util/src/lib.rs#L233-L246

So this might be as simple as iterating over the `errors` and `warnings` in backwards if a flag is present in the linked section above.
