### ISSUE TITLE
compare Sway LSP results to Rust (Analyzer) results

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/sway#387]
As Sway compiler improves, so does our Language-Server, some of the current implemented LSP features offer modest response, compare the features to the way Rust LSP does it and if possible improve Sway LSP to match Rust's response.

This is a good first issue in order to get familiar with the codebase of language-server.

**Comment by JoshuaBatty** [comment]
I have spent some time working out an optimal workflow for the above goal. I'll present my workflow below in case it helps other people.

## Set up verbose tracing in VScode for both Sway and Rust
We can see the request and response json messages sent between the client and server by enabling verbose logging for each lsp. Open _Settings_ in VScode, and search for _tracing_. Then, set both `sway` and `rust-analyzer` to have verbose logging, see below. 

<img width="1047" alt="enable vscode tracing" src="https://user-images.githubusercontent.com/1289413/160311908-ba3397cd-796f-49b9-a08d-3a07f2919f1a.png">

## Create identical Sway and Rust projects
To accuratly compare the responses from `sway-lsp` and `rust analyzer`, it helps to have a sway and rust project that has as near identical code as possible. I've created an example rust and sway project that can be cloned from here if you want instead of creating your own. [See here](https://github.com/JoshuaBatty/lsp-test-projects/tree/main/Particle).

## Automate the development set up.
I decided to create a bash script that opens up the two example projects with the trace windows open and open up `sway-lsp`. Below you can see the `bash` script I wrote along with how my VSCode windows open up. 

bash file code.
```
#! /bin/sh
cd /Users/joshuabatty/Documents/rust/fuel_test_projects/lsp_sway_project
code . -n -g src/main.sw
cd /Users/joshuabatty/Documents/rust/fuel_test_projects/lsp_rust_project
code . -n -g src/main.rs
cd /Users/joshuabatty/Documents/rust/fuel/sway/sway-lsp
code . -n -g src/server.rs
```

<img width="1026" alt="lsp comparison" src="https://user-images.githubusercontent.com/1289413/160312524-840566ce-1f6b-41a8-82fd-393f9f3a8e0e.png">

## Compare the output windows
For example, if wanting to work on hover functionality, hover over a token in the rust project, then hover over the same token in the sway project, and compare the response from each and confirm that they are identical.
