### ISSUE TITLE
Emit a warning when all the variants are covered but the user adds a redundant wildcard pattern

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#3949]
Nice!  Are we emitting a warning when all the variants are covered but the user still adds a (redundant) wildcard pattern?  I'm pretty sure Rust does this.

Edit: I just checked, and we don't.  I think this should probably be an issue?

_Originally posted by @otrho in https://github.com/FuelLabs/sway/issues/3790#issuecomment-1407825975_

**Comment by sdankel** [comment]
> Are we emitting a warning when all the variants are covered but the user still adds a (redundant) wildcard pattern?

I agree that we should be emitting a warning, but I don't think it needs to be a specific warning for this one case. The `MatchExpressionUnreachableArm` is designed for this and is clear enough.

**Comment by ironcev** [comment]
> The MatchExpressionUnreachableArm is designed for this and is clear enough.

@sdankel I would love to get your view on the topic on error messages, like how specific, how detailed, etc. they should be. It looks to me that you are in the "short and simple" camp :-) Different approach, with specific messages, specific explanations etc can be seen in the PR that tries to close this issue: https://github.com/FuelLabs/sway/pull/4965

Also, this particular comment on the [Expressive Diagnostics RFC](https://github.com/FuelLabs/sway-rfcs/pull/30#issuecomment-1682280094) calls for discussing exactly that topic.

If you can contribute with your view that would be great.

**Comment by ironcev** [comment]
> The MatchExpressionUnreachableArm is designed for this and is clear enough.
For the clarification, we are actually using the `MatchExpressionUnreachableArm` warning here and not introducing a new one. It's just the specific additional message and contextual information of the warning that describes the issue in more detail. This is what we want to achieve with Expressive Diagnostics, less error/warning types like ` MatchExpressionUnreachableArm` and richer explanations that try to pinpoint the issue.

BDW, to the question if this case deserves a different treatment at all, I am for yes. Coming from C# where the language kinda forces you to have the catch-all at the end, putting it immediately was the default and ending up in the "oh I don't need this" was always a bit of a surprise. I am definitely for welcoming to Sway programmers with different backgrounds, and perhaps because of this experience I had I am for add specific information for this case.
