### ISSUE TITLE
`forc-test`: Run all unit tests concurrently

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3953]
We've been holding of from running tests concurrently to keep forc-test relatively simple and easy to debug while we role out new features, but users are already getting to the point where test execution can be a bottleneck in their workflow so we should consider tackling this soon.

The current design is very concurrency-friendly - we should be able to use something like [`rayon`](https://docs.rs/rayon/latest/rayon/) to trivially distribute test execution over the available cores, where each test gets its own interpreter and copy of the bytecode.

**Comment by mitchmindtree** [comment]
> Maybe i'm missing something here but isn't this just adding rayon and calling par_iter() instead of iter() here?

Yep, we've definitely been trying to write `forc-test` in a way that makes it that easy :)

> Granted, it still took <1s to test, but it was about 3x slower, so its slower nonetheless.

It could be worth finding a project that has a more significant number of tests - I think @nfurfaro mentioned he has a chess app with loads of tests that could benefit?

**Comment by bingcicle** [comment]
I took a look again at the previous conversation and it seems like the time bottleneck was in building and not in testing. The error in testing was with the size of the bytecode:

> ...I can no longer run forc test successfully because of the size (1544416 bytes), which is > max TransactionScriptLength.

**Comment by mitchmindtree** [comment]
Yeah the bytecode is a bit of an issue for `forc-test` as well. Unfortunately, we can't re-use the same bytecode for every test, as we need to modify the jump instruction at the beginning of the bytecode to jump to the correct test entry point for each. This means we end up needing to clone the entire bytecode for each test to support parallelism, as the interpreter requires the bytecode as a full slice of bytes (so that it can jump around etc). One approach could be to re-use the same N number of bytecode slices where N is the number of cores (so that we don't clone 100s of slices for huge projects). Still not ideal, but even a few MB * number-of-cores shouldn't be *tooo* much RAM usage.

**Comment by bingcicle** [comment]
So, I looked further into this and think I figured out what is keeping the concurrent version from keeping up with the serially-ran tests - the tests themselves aren't the bottleneck, but it is that we collect the results afterwards for printing - I think there is non-significant work involved in having to wait for the processes to finish/sync results before printing the summary. Doing a `for_each()` ended up allowing my local forc to be competitive with running it serially.

With that said... it doesn't seem like there's much speed improvement from this that maybe we can hold this off for now maybe?

It seems like the bottleneck raised by @nfurfaro had to do the **building** and not necessarily the **testing**, unless I'm missing something?

**Comment by nfurfaro** [comment]
Indeed, it seems the issues I was having were related to building. The tests actually ran quite fast once the build was done.

**Comment by kayagokalp** [comment]
Hmm i have some initial benchmarks ready. In my tests on my m1 max 32 gb system it looks like parallel version is faster than serial version if both of them built in release mode. My guess is that with tests that actually does contract calls this speed-up will be visible as individual tests tend to take longer. Each parallel runner deploys their own storage which might make the difference more visible with contract calls. I will post an update.


The following runs are taken from 10 runs:
<img width="610" alt="Screen Shot 2023-04-03 at 11 54 52" src="https://user-images.githubusercontent.com/20915464/229601110-d057c1b3-13bb-4525-b887-46b07e32f74a.png">

**Comment by kayagokalp** [comment]
A little bit going deeper, I introduced more complex tests and expanded the number of tests so that execution time takes longer. Results are interesting, but not that much to go into it in more details as we don't have a specific real example that execution is bottleneck.

I think there is some false sharing happening, or at least that is what is happening on my 128 byte cache-line system. It is important to note that 128 byte of cache-line a little unorthodox, most of the non-m1 chips I have interacted with so far has 64 byte cache lines. Aligning for the cache lines yields extra %2-3 speed-up which is negligible but consistent so false sharing might be the case but generally, at least in my experience, effects of false sharing tend to be higher so I am not entirely sure if that is the case.

I am thinking of just converting `iter()` to `par_iter()` for now and let the compiler optimizations do their tricks. As i posted in the above comment with release mode builds we still have some speed-up. If we exclude building step it is around 1.5-2x. If we include the building step (i.e the whole time the process is taking) speed-up is around %3-4 as most of time spent during building overall as Bing mentioned in his previous exploration on this issue.
