### ISSUE TITLE
Support storage of heap types in a more generic way.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#4013]
I'm wondering if it perhaps would be more sustainable to have a Storage type that could be used universally for storing heap types in place of having a `StorageVec` , a `StorageBytes`, `StorageString`, etc...
Otherwise, we may be adding 1 new Storage type for each new heap type added to the stdlib.

Off the top of my head, I thought that maybe `StorageSlice` might be a good candidate, as most (all?) heap types should be convertible to a `raw_slice` type.

Not a fully baked idea, but worth putting out there to see what other team members think.

cc @mohammadfawaz 
ref #2465

**Comment by bitzoic** [comment]
I have been thinking about how this can be done and following the `StorageSlice` principle, propose the following solution. To be clear, this does not eliminate the need for adding 1 new Storage type for each new heap type added to the stdlib, but rather simplifies the addition of these types.

We still require a `StorageBytes`, `StorageString`, etc for each type since we are inherently unable to initialize heap types in a storage block i.e.
```rust
storage {
     my_bytes: Bytes: Bytes { 
          buf: RawBytes { 
               ptr: ???,
               cap: 0
          },
          len: 0
     }
}
```


# Possible Approach: 
A `StorageSlice` struct would be capable of storing these types. But the storage block would look as so for different types:

```rust
storage {
     my_bytes: StorageSlice = StorageSlice { },
     my_string: StorageSlice = StorageSlice { },
}
```
This can make it difficult to differentiate between what the stored type is intended to be and I would discourage this implementation.

We could have `StorageBytes` struct use the `StorageSlice` struct, however this doesn't make much sense. The `StorageSlice` type would need to implement `fn store(key: b256, slice: raw_slice)` without the inclusion of `self` as an argument in order for `__get_storage_key()` to be passed from `StorageBytes`, defeating the purpose of a `StorageSlice` struct in the first place.

# Recommended Approach:

Since these heap types can all be converted into a `raw_slice`, a `fn store_as_slice(slice: raw_slice, key: b256)` and `fn load_slice(key: b256) -> raw_slice` functions can work alongside the existing `store()` and `get()` functions in `storage.sw`.

With these functions in place, a `StorableSlice` trait can allow us to implement these functions to any `Storage[MyType]` type without repeating existing code. For example:

```rust
pub trait StorableSlice<T> {
    #[storage(write)]
    fn store(self, argument: T);
    #[storage(read)]
    fn load(self) -> T;
    #[storage(read)]
    fn len(self) -> u64;
}
```

This trait could be easily implemented for `StorageString` like so:

```rust
impl StorableSlice<String> for StorageString {
    #[storage(write)]
    fn store(self, string: String) {
        let key = __get_storage_key();
        store_as_slice(string.into_raw_slice(), key);
    }

    #[storage(read)]
    fn load(self) -> String {
        let key = __get_storage_key();
        String::from_raw_slice(load_slice(key))
    }

    #[storage(read)]
    fn len(self) -> u64 {
        load_slice_len(__get_storage_key())
    }
}
```
To use the implementation above in our smart contract would be done in the following manner:

```rust
storage {
    my_string: StorageString = StorageString {},
}

#[storage(write)]
fn store_my_string(vec: Vec<u8>) {
    let mut vec = vec;
    let string = String::from_vec_u8(vec);

    storage.my_string.store(string);
}
```

Unless changes are made beyond the stdlib, I believe this to be the best approach to handling heap types in storage and will open an issue to introduce the `StorableSlice<T>` trait to the stdlib.
