### ISSUE TITLE
compiler verification failure

### ISSUE THREAD

**Issue by jtriley-eth** [FuelLabs/sway#4029]
## Description

When defining a generic function where the generic type implements (explicitly) `Ord` and `Eq`, using it on `b256` types produces a verification error.

## Behavior

The following script, when `forc test` (versions `0.33.1` and `0.34.0`) is run, should pass. However, it produces the error following the code snippet.

```rust
script;

use core::ops::*;

const ZERO_B256: b256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
const ONE_B256: b256 = 0x0000000000000000000000000000000000000000000000000000000000000001;

fn generic_compare<T>(a: T, b: T) -> bool where T: Ord + Eq {
    a < b
}

fn main() -> bool {
    generic_compare(ZERO_B256, ONE_B256)
}

#[test]
fn test_works() {
    assert(main());
}
```

Error:

```
error: Internal compiler error: Verification failed: Type mismatch found for call to 'neq_4'.
Please file an issue on the repository and include the code that triggered this error.
```

Error with `RUST_BACKTRACE=full`:

```
Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/backtrace.rs:332:13
   3: std::backtrace::Backtrace::capture
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/backtrace.rs:298:9
   4: anyhow::error::<impl anyhow::Error>::msg
   5: forc_pkg::pkg::compile
   6: forc_pkg::pkg::build
   7: forc_pkg::pkg::build_with_options
   8: forc_test::build
   9: forc::cli::commands::test::exec
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: forc::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/core/src/ops/function.rs:606:13
  16: std::panicking::try::do_call
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panicking.rs:483:40
  17: std::panicking::try
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panicking.rs:447:19
  18: std::panic::catch_unwind
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panic.rs:137:14
  19: std::rt::lang_start_internal::{{closure}}
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/rt.rs:148:48
  20: std::panicking::try::do_call
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panicking.rs:483:40
  21: std::panicking::try
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panicking.rs:447:19
  22: std::panic::catch_unwind
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panic.rs:137:14
  23: std::rt::lang_start_internal
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/rt.rs:148:20
  24: _main
```

## Steps to Reproduce

- Use `forc` version `0.34.0`
- Copy-paste the code above (or impl any generic function with `where T: Ord + Eq`)
- Pass arguments of type `b256` to the generic function
- Run a test function

**Comment by mohammadfawaz** [comment]
Alright so first, changing `where T: Ord + Eq` to `where T: Ord` is a workaround in this case. The issue is that when we say `T` has to implement `Eq`, the implementation of `eq()` for `b256` is "discovered" which is correct. However, in the [implementation of `lt`](https://github.com/FuelLabs/sway/blob/d77cafd0c23bce4591f81e30910802cddf285e12/sway-lib-core/src/ops.sw#L305), we use `neq` on a `u64` which requires `eq`, and we seem to be confusing the two implementation of `eq` and `neq` for some reason. I.e., we're using the `neq` for `b256` to compare the two `u64`s in the implementation of `lt` for `b256`, which I linked to above.

Seems to me like another instance where the trait constraints solver is getting confused. cc @emilyaherbert.

**Comment by emilyaherbert** [comment]
A quick debugging pass shows that this also solved by removing the `use core::ops::*;` import. My initial hypothesis is that this PR and #3946 are failing for the same reason.

> Also, if I changed the neq to eq in he [implementation of lt](https://github.com/FuelLabs/sway/blob/d77cafd0c23bce4591f81e30910802cddf285e12/sway-lib-core/src/ops.sw#L305), I don't get the problem.

This is very interesting! That gives me hope this bug might be caused by some failure to resolve trait _methods_, which would be a quicker fix than the aforementioned bug. I'll take a deeper look to diagnose.
