### ISSUE TITLE
`__get_storage_key()` is not listed as a compiler intrinsic in the Sway Book

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4071]
The Sway book has a section on compiler intrinsics. The `__get_storage_key()` function is not documented here.

**Comment by mohammadfawaz** [comment]
I intentionally omitted `__get_storage_key` in that section because this intrinsic is really hard to use and is not very well defined. It currently works in the way it's used in the standard library but it is certainly non-obvious _how_ to actually use it. The good news is that https://github.com/FuelLabs/sway-rfcs/pull/23 will help avoid users or even library authors having to worry about it, at which point we can just deprecate it.
