### ISSUE TITLE
`sha256` gives erroneous results in some cases

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#4491]
`std::hash::sha256` gives wrong results for some strings, including `"test"`:

```sway
script;

use std::hash::sha256;

fn main() {
  // should be 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
  log(sha256("test")); 
  /*
    {
    "LogData": {
      "data": "9134a6432bb8da899b9005e41957835454b289f01b21f6f0373da8bcaac5c251",
      "digest": "4a5c62befb83ded8c020ca5cc13c7f8b059d331ab068a4e123735c9df999cdc1",
      "id": "0000000000000000000000000000000000000000000000000000000000000000",
      "is": 10344,
      "len": 32,
      "pc": 10452,
      "ptr": 10912,
      "ra": 0,
      "rb": 0
    }
  },
  */

  // should be 4a3cd7c8b44dbf7941e55179425f746adeaa97fe2d99b571fffee78e9b41743c
  log("Fastest Modular Execution Layer!");
  /*
    {
    "LogData": {
      "data": "46617374657374204d6f64756c617220457865637574696f6e204c6179657221",
      "digest": "4a3cd7c8b44dbf7941e55179425f746adeaa97fe2d99b571fffee78e9b41743c",
      "id": "0000000000000000000000000000000000000000000000000000000000000000",
      "is": 10344,
      "len": 32,
      "pc": 10456,
      "ptr": 10504,
      "ra": 0,
      "rb": 1
    }
  },
  */
}
```

**Comment by Braqzen** [comment]
With a little bit of manual testing it appears that strings of length which are not a multiple of 8 produce incorrect hashes.
Afaik the compiler pads to a word before the registers are hit so I assume the strings get padded which results in a different hash.

**Comment by esdrubal** [comment]
This issue appears to occur as Braqzen mentioned because of padding.

https://github.com/FuelLabs/sway/blob/dc67807a22f6903b927180e7cf925655d6a49f1c/sway-core/src/asm_generation/from_ir.rs#L207

The line above makes `__size_of::<T>()` return 8 instead of 4 for the string "test". So the code below fails:
https://github.com/FuelLabs/sway/blob/dc67807a22f6903b927180e7cf925655d6a49f1c/sway-lib-std/src/hash.sw#L17-L21

I suspect we cannot simply change `__size_of` to return unpadded values for strings.
Should we consider adding a new intrinsic such as `__size_of_unpadded` ?
