### ISSUE TITLE
All integers are treated a u64

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#4646]
Sway currently only handles overflow for u64. Other integer types are just treated like a u64 and can contain larger values than they should be allowed to represent.

For instance this test does *not* panic and instead logs a value that is larger than `U32_MAX`:
```
#[test]
fn test_over_flow_works() {
    let a: u32 = 4294967295;
    let b: u32 = 10000; 

    let result: u32 = a + b;
    log(result);
}
```

**Comment by anton-trunov** [comment]
It seems to me this issue needs to be split into two PRs.

One PR would fix the integer conversion during IR generation as per the
following comment in the sway-core/src/ir_generation/convert.rs file:

> // In Sway for now we don't have `as` casting and for integers which may be implicitly cast
> // between widths we just emit a warning, and essentially ignore it.  We also assume a
> // 'Numeric' integer of undetermined width is `u64`.  The IR would like to be type
> // consistent and doesn't tolerate mising integers of different width, so for now, until we
> // do introduce explicit `as` casting, all integers are `u64` as far as the IR is
> // concerned.

We might want to first get rid of implicit integer conversions (https://github.com/FuelLabs/sway/issues/3470) while handling this issue.

And the other PR would fix assembly generation, because currently all basic
integer binary operations in IR get compiled as native (`u64`) FuelVM
instructions, so e.g. `u32` overflows are not handled during this stage.
The trickier part would be to emulate at the level of VM instructions arithmetic overflows/underflows for bit widths strictly less than 64.

cc @vaivaswatha

**Comment by anton-trunov** [comment]
In an internal discussion @vaivaswatha commented that another approach would be to only have 64-bit arithmetic operations in the compiler and handle the issue at the Sway level by implementing overflowing 8/16/32-bit operations in the standard library. This simplifies the compiler a lot and if generated assembly is not efficient enough this is going to be an optimizer issue. This also eliminates the need to change IR generation.

Also, it seems 8/16/32-bit operations are not going to be a common use-case so introducing some overhead here should be fine (this overhead is unavoidable for a 64-bit VM anyways).
