### ISSUE TITLE
Enhancement: consider if a clippy build  termination check for warnings flag is useful

### ISSUE THREAD

**Issue by d3287t328** [FuelLabs/sway#4678]
On this line: https://github.com/FuelLabs/sway/blob/26581f5937c556878a9b20311cb0a258bdf944d6/ci_checks.sh#L19

Would there be any value in adding the -D flag? with `-D warnings` the build could be terminated on any warnings. While I could see this is annoying it might also improve reliability of the codebase.

**Comment by kayagokalp** [comment]
Hey @d3287t328, we actually have it with `-D` flag in the CI.
https://github.com/FuelLabs/sway/blob/26581f5937c556878a9b20311cb0a258bdf944d6/.github/workflows/ci.yml#L198-L210

But it totally makes sense to do that in the script as well so that script simulates the CI as accurate as possible. Thanks for the issue!
