### ISSUE TITLE
AST item annotation system (pure/read/write/chain for storage access)

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#470]
We should support an annotation system for AST items. This is blocked by #252, as the annotation system will inherently be coupled with the parser.

Generically, we should be able to tag items with `#[annotation]`. This annotation system will then be used to implement storage usage annotations regarding purity and impurity, as the comments describe.

old issue text:
---

Do we want to keep `impure`? Do we want to do something else? See #466 for more discussion and context.

---

Options so far:
1. `fn impure` instead of `impure fn`
2. `ifn`
3. `imp fn` or `fn imp`
4. `fn foo() -> impure u64`
5. `fn_impure` or `fn_with_effects`

Additionally, the default right now is pure for everything, impure if specified. We should also bikeshed if we want to keep that or switch to impure by default.

cc @nfurfaro @adlerjohn @SilentCicero 

---

**Comment by adlerjohn** [comment]
Aside from `impure` specifically, could we have 4 purity levels?

1. `pure` (default, could be omitted?): function does not touch any state.
2. `view_chain` (name up for debate): function does not touch contract state but touches chain state (e.g. block height).
3. `view`: function does not write contract state.
4. `impure`: function writes contract state.

**Comment by mitchmindtree** [comment]
Before moving this into an attribute, it'd be nice to clarify the semantics for attributes more generally going forward.

It sounds like there are no plans to use the attribute syntax for procedural macros like Rust does. I'm all for avoiding macros unless we come across some dire need! But maybe it's worth considering whether we still want to reserve their use to distinguish between user-definable, compile-time reflection (like `derive`, or lints) and non-user-definable (language-level stuff like function visibility and purity).

If we don't want to reserve them to signal "user-definable" reflection, then what do they really mean in sway other than another syntax for writing keywords? Maybe that alone is enough motivation for them as a feature - simply to allow for an unordered set of keywords so that users don't need to remember the order of `[visibility] [purity] fn [ident]`, etc?

---

Fwiw, imo,

```rust
impure fn some_method() {
    storage.some_var = 0;
}
```

is quite a bit cleaner than

```rust
#[allow(impure_function)]
fn some_method() {
    storage.some_var = 0;
}
```

To me, the latter implies that `impure_function` is a lint of some kind that we're allowing to pass, when it's a language requirement for functions that want to touch some storage. This might just be my overly Rusted perspective though! And I can empathise with the cluttered function signature trauma solidity users might have :smiling_face_with_tear:

**Comment by adlerjohn** [comment]
An alternative could be

```rust
#[state_mutability(view)]
fn foo() {
}
```

In other words, reserving the function signature for _functionality_ and pushing _properties_ to attributes.

**Comment by mohammadfawaz** [comment]
I like 
`#[state_access(none)]` instead of `pure`, 
`#[state_access(read_only)]` instead of `view`, 
`#[state_access(read_write)]` instead of `impure`.
Not sure about the fourth mode yet. 
I know that `pure` comes from Solidity, but I don't find it self explanatory. I know that the above attributes are more verbose, but I think it is very clear what they do. Also, using attributes means we're not restricted to short single word keywords.

**Comment by mitchmindtree** [comment]
Maybe for consistency with the `storage` keyword it could be `storage_access` instead of `state_access`?

**Comment by mohammadfawaz** [comment]
I like that better yes. So:
`#[storage_access(none)]` instead of pure,
`#[storage_access(read_only)]` instead of view,
`#[storage_access(read_write)]` instead of impure.

**Comment by mitchmindtree** [comment]
Or potentially even just `#[storage(...)]` leaving `access` implied?

```rust
#[storage()] // default case when `storage` attribute is omitted 
#[storage(read)]
#[storage(read, write)]
#[chain(read)]
```

or something along these lines?

**Comment by nfurfaro** [comment]
I feel like  `pure`  is pretty clear to anyone with either some functional programming or Solidity background, but otherwise, its meaning could be kind of vague.
As long as we're going in the direction of trying to keep the function signature as uncluttered as possible, then I think something like the proposal by @mitchmindtree above is the way to go. However, I think its reasonable to expect developers to learn about the different levels of state access well enough that a simple, single-word attribute should suffice., ie:
`#[pure]` // default, MAY be ommitted.
`#[read]` // can only read from storage
`#[write]` // MAY read from storage, can write to storage
`#[chain]`// can read chain state

But, I don't feel that a single keyword before a function is too much either. Just as we add `async` to a function definition, 
the type of side effects a function may potentially have doesn't seem over the top. 
But then if we start adding `payable`/`non-payable`  keywords and others, yeah that gets kind of ugly.

**Comment by otrho** [comment]
> In that call we had also decided to omit purity specification on traits, leaving it up to the implementation. It is not hard to conceive of an interface which could be implemented either with storage or without storage. Trait writers would have to provide both a pure and impure version of the trait, which I don't feel is necessary.

OK, so no attributes for ABI or trait interface signatures.  But what about trait methods?  I'm thinking still no, they can perhaps inherit their purity from the implementation of the trait, though that can get complicated and/or ambiguous.

And how about `impl` self methods?  I'm guessing they're similar to top-level functions and so storage attributes do apply.

**Comment by otrho** [comment]
I guess `impl` methods are really just UFCS sugar and so the impurity really only applies to calling the actual methods, and instantiating or passing such a struct isn't impure.

**Comment by nfurfaro** [comment]
>and so the impurity really only applies to calling the actual methods

^^ this.

**Comment by sezna** [comment]
I think the issue of checking actual storage accesses (`asm` storage opcodes, `storage` syntax) against the surrounding context can be decoupled from annotating AST items and checking that the annotations are accurately permissive, for the sake of smaller PRs.

**Comment by mitchmindtree** [comment]
@adlerjohn thoughts on:

- `#[storage(read)]`
- `#[storage(write)]`
- `#[chain(read)]`

rather than `state`? I'm just thinking that the word `storage` might be more consistent with the `storage` declarations, whereas `state` currently seems a bit ambiguous?

**Comment by adlerjohn** [comment]
We could separate `state` into `storage` (contract storage) and `chain` (blockchain state), but I'm not sure we necessarily need that level of granularity yet. Not explicitly against but just noting that I haven't heard anyone complain about `view` in Solidity encompassing both storage reads and chain state reads.

**Comment by mitchmindtree** [comment]
Even if we don't need the granularity today but are considering it, I think the more conservative choice would be to go for the more granular approach to start and then implement the short-hand on top of it. If we're to start with the short-hand but change our minds in the future, that would involve a bit more breakage or deprecation in users' code.

I think it also feels a bit asymmetrical if `state(read)` means you can read from chain, but `state(write)` doesn't mean you can write to it. Not being able to write to blockchain is perhaps obvious to us as writers of a blockchain, but maybe not so obvious to future Sway newbies?

As a Sway code reader, I can see myself appreciating the extra insight into the kinds of side-effects that are happening by glancing at the attribute, but that's likely just my personal preference!

**Comment by adlerjohn** [comment]
Makes sense, no objection.

**Comment by otrho** [comment]
OK, now I'm having to decide whether multiple `storage` attribs are OK.  I was initially going to ban them, but it might be valid to have:
```
#[storage(read)]
#[storage(write)]
fn foo() { ... }
```
to be equivalent to 
```
#[storage(read, write)]
fn foo() { ... }
```
I'm guessing nobody will have a strong opinion either way and the former is probably just fine?

**Comment by mitchmindtree** [comment]
Yeah treating attributes like a "set" and having them merge like that sounds good!
