### ISSUE TITLE
Formatter removes `//!` comments at the top of the file

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#5058]
Related https://github.com/FuelLabs/sway/issues/5052

**Comment by sdankel** [comment]
@eureka-cpu You said you fixed this before, do you want to take a look at why this regressed?

**Comment by eureka-cpu** [comment]
If @cr-fuel is keen to take it on that's fine w me

To give some context, I implemented the module level doc comments in the compiler to be able to get documentation working for `forc-doc` and somewhere along the way before then they were just treated as regular comments. There was an issue at where they were getting removed, I'm pretty sure I solved that long before adding them to the compiler. I'll try to find the issue/PR.

**Comment by eureka-cpu** [comment]
I was mistaken, I actually just solved the problem for comments at the beginning of a file. The reason they are being removed is likely because they are a somewhat new addition to the compiler and may not have been corrected in the formatter yet.

Here are the relevant PRs that added in module level doc comments: #4081 #4113 

Here is where you will likely need to begin tracking the bug down: https://github.com/FuelLabs/sway/blob/master/swayfmt/src/utils/language/attribute.rs#L82 

Hope that helps, let me know if you have any questions

**Comment by andrewvious** [comment]
I've got it fixed, opening a PR now.
