### ISSUE TITLE
`forc test` not recognizing tests in contracts

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#5136]
From @bitzoic 

1. Create a new toolchain fuelup toolchain new v0.46
2. Install Forc fuelup component add forc@0.46.0
3. Install Fuel-core fuelup component add fuel-core@0.20.4
4. Create a new folder mkdir forc_test
5. Init a new project forc init
6. Add a test
7. Run forc test

```sway
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}

#[test]
fn my_test() {
    assert(false);
}
```
This SHOULD fail. Yet I get that no tests were run

**Comment by kayagokalp** [comment]
Seems like compiler is no longer preserving test entries after d2dbacbce27e2906e11825d23865a4752b79bdd0f5006cd2a7415ecbdec192b3 only for contracts.

**Comment by kayagokalp** [comment]
My guess is the following:

While compiling contracts `forc-test` compiles without tests fist, maybe cache is used while compiling it with tests. Since the file does not change the cache is going to be hit always for tests included version although we want to compile it with tests.

We can check if current path is pointing to a contract and check tests included parameter, if that is the case we can omit the cache.

**Comment by kayagokalp** [comment]
This is happening because module cache is only using paths as key. But same source file (same path) compiled with and without tests yields different AST and thus needs different entries in the module cache.
