### ISSUE TITLE
bug: `CallPath` prefixes are empty for `TyImplTrait`s if the path is not given in the `impl` block

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#5204]
```sway
library;

use core::ops::Eq;
use ::convert::From;

impl Eq for String { ... }
impl From for String { ... }
```
With the above examples, whether the trait being implemented is from the project or a dependency, if it is declared in the `use` statement but not in the `impl` block the `CallPath` prefixes are empty.

Whether it's a dependency or not, they look the same, here's some debug output:
```sh
CallPath {
    prefixes: [],
    suffix: BaseIdent {
        name_override_opt: None,
        span: Span {
            src (ptr): 0x0000555558f0b2c0,
            source_id: Some(
                SourceId {
                    id: 51,
                },
            ),
            start: 6001,
            end: 6005,
            as_str(): "From",
        },
        is_raw_ident: false,
    },
    is_absolute: false,
}
```

Could be a separate issue, but we also don't store the `CallPath` prefixes of the type being implemented on. So in the `TyTraitImpl` `implementing_for` field, which is type `TypeArgument`, the `CallPathTree` is missing that type's prefixes.

```sh
TypeArgument {
    type_id: TypeId(
        101106,
    ),
    initial_type_id: TypeId(
        15723,
    ),
    span: Span {
        src (ptr): 0x0000555558f0b2c0,
        source_id: Some(
            SourceId {
                id: 51,
            },
        ),
        start: 6021,
        end: 6027,
        as_str(): "String",
    },
    call_path_tree: Some(
        CallPathTree {
            qualified_call_path: QualifiedCallPath {
                call_path: CallPath {
                    prefixes: [],
                    suffix: BaseIdent {
                        name_override_opt: None,
                        span: Span {
                            src (ptr): 0x0000555558f0b2c0,
                            source_id: Some(
                                SourceId {
                                    id: 51,
                                },
                            ),
                            start: 6021,
                            end: 6027,
                            as_str(): "String",
                        },
                        is_raw_ident: false,
                    },
                    is_absolute: false,
                },
                qualified_path_root: None,
            },
            children: [],
        },
    ),
}
```

Adding the path directly in the `impl` block fixes it, but I would expect some consistency in this case, that whether a user uses an import statement or gives the path in the `impl` block, it should yield the same result in the AST.
```sway
library;

impl core::ops::Eq for String { ... }
impl ::convert::From for String { ... }
```

**Comment by sdankel** [comment]
I think this is the issue: https://github.com/FuelLabs/sway/blob/9c26840336afe03759b09df9a96658378d35ac56/sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs#L305C30-L305C30

It's possible that this could be fixed by calling `CallPath::to_fullpath` on this call path before it's used in the `TyImplTrait`

**Comment by IGI-111** [comment]
I do not think converting the trait name to a fullpath is warranted here and I'd like to understand why you want to do that before considering it.

**Comment by IGI-111** [comment]
I'm closing this because there doesn't seem to be a bug.

If one wants to get the canonical path of a type expression they should indeed turn it to a fullpath, but this is not what we want to store here. If what's required is a reference to the actual declaration or the full path of the type being implemented for/trait being implemented, then this can either be produced on demand on the `forc-doc` side or produced by the compiler and stored in a separate field. But these prefixes being empty isn't wrong. We need to know what the original source expression looks like.

Feel free to reopen if I'm missing something obvious here.

**Comment by eureka-cpu** [comment]
The issue is that a `TyImplTrait` that has the path specified in the `impl` block itself produces a different AST representation than one that uses a `use` statement. I had expected that use `x::y::Z; impl Z for MyType` would produce the same AST as `impl x::y::Z for MyType` but they do not.

I found it strange, since `impl x::y::Z for MyType` does produce the full prefixed `CallPath` but using an import statement to simplify this, does not.

Your explanation does make sense though, and I believe you're correct. There are other ways of getting the full path, and this issue can remain closed.

Thanks 🙂
