### ISSUE TITLE
Wrapping `__addr_of` in a function results in incorrect compilation

### ISSUE THREAD

**Issue by vaivaswatha** [FuelLabs/sway#5232]
The test `ptr_no_issue()` succeeds while `ptr_issue()` fails. The only difference b/w them being that `__address_of` is called from a wrapper in the latter.

```
script;

fn main() -> u64 {
   0
}

struct A {
  a: u64,
}

struct B {
  a: A,
  x: (u64, u64),
}

#[test]
fn ptr_no_issue() -> u64 {
    let a = A { a: 11 };
    let mut b = B { a: a, x: (11, 11) };

    let mut ptr_b = __addr_of(b);

    b.x.0 = 111;
    assert(b.x.0 == 111);
    assert(ptr_b.read::<B>().x.0 == 111);

    42
}

#[test]
fn ptr_issue() -> u64 {
    let a = A { a: 11 };
    let mut b = B { a: a, x: (11, 11) };

    let mut ptr_b = ptr(b);

    b.x.0 = 111;
    assert(b.x.0 == 111);
    // FAILS: b is not changed at all.
    assert(ptr_b.read::<B>().x.0 == 111);

    42
}

fn ptr<T>(t: T) -> raw_ptr {
    __addr_of(t)
}
```

```
$ forc test
...
  Running 2 tests, filtered 0 tests
      test ptr_no_issue ... ok (192.545µs, 92 gas)
      test ptr_issue ... FAILED (192.541µs, 78 gas)

   failures:
      - test ptr_issue, "src/main.sw":30 
        revert code: ffffffffffff0004 -- Failing call to `std::assert::assert`
        Logs: []
```

Credits to @ironcev for finding this.

**Comment by ironcev** [comment]
@vaivaswatha As you properly pointed it out, `ptr<T>` actually has the proper behavior. Defined as it is, it should return the pointer to its local copy of `b` since we have the pass-by-value semantics for the parameter `t`. This of course opens the issue of returning a pointer to a value on a local stack, but that's the other issue to solve (error? warning?).

So I would close this issue, because fixing it would mean having the behavior that we actually do not want to have as you mentioned.

However, we still do have an issue with the pass-by-value semantics when using pointers in callees and I've opened a separate isse for that: #5250

**Comment by vaivaswatha** [comment]
Closing this in favour of #5250 .
