### ISSUE TITLE
Improve the way plugins are selected

### ISSUE THREAD

**Issue by crodas** [FuelLabs/sway#5402]
This is another enhancement on top #5396. The plugins are currently selected by scanning `$PATH`. This behaviour should be the fallback strategy, the first strategy should be to scan the directory where the current `forc` binary is being stored.

Context: https://forum.fuel.network/t/mystical-mistake-on-the-sames-toolchains/3867/6

**Comment by PaulZhemanov** [comment]
@crodas how can i now fix my problem?

**Comment by PaulZhemanov** [comment]
@crodas i got this
``^^>>> echo $PATH | tr ':' '\n' | xargs -I{} find {} -type f -name "forc-*" | sort                                        17:45:04 
xargs: command line cannot be assembled, too long``

**Comment by PaulZhemanov** [comment]
@crodas 
<img width="692" alt="image" src="https://github.com/FuelLabs/sway/assets/133055914/d03b1e90-952c-49b1-a6d4-0a5eca7a6704">

**Comment by chlenc** [comment]
<img width="648" alt="image" src="https://github.com/FuelLabs/sway/assets/35231749/9b31f4a7-9ab9-4a99-b8da-c22a536faa58">

**Comment by PaulZhemanov** [comment]
@crodas it looks like problem you describe for @chlenc, not for me . but i have problem with building contract..

**Comment by PaulZhemanov** [comment]
@crodas  The problem is that the small contract we posted on the forum builds without any issues for me, but Alex is facing problems with the build. However, in the real project we are working on, I'm the one having build issues, not Alex. The contract on the forum is just a demonstration that the compiler behaves differently with absolutely identical versions.

**Comment by PaulZhemanov** [comment]
@crodas help us
