### ISSUE TITLE
Internal Compiler Error when evaluating nonsensical `const`

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#5616]
Swapping `let` for `const` in places can lead to an ICE among other errors.

The following minimal example:

```sway
contract;

abi Abi1 {
    fn foo() -> b256;
}

abi Abi2{
    fn bar() -> u64;
}

pub fn main() {
    let contract_1 = abi(Abi1, b256::min());
    const invalid_const = contract_1.foo();
    let contract_2 = abi(Abi2, invalid_const);
    let invalid = contract_2.bar();
    log(invalid);
}

```

Produces:

```
error: Internal compiler error: Unable to resolve variable 'invalid'.
Please file an issue on the repository and include the code that triggered this error.
```

**Comment by jjcnn** [comment]
I 've been looking at this one, and I can't reproduce the ICE neither on `master` nor any of the tagged branches since `0.48.0`.

The example code gives me a warning about how the `const` variable should be in all caps, but other than that everything compiles just fine.

On the playground I'm getting 

```
There was an unexpected error compiling your contract. Please try again.
```

This seems unrelated, though, because I'm getting it even if I change `const` to `let`.

Can you walk me through the exact steps I need to go through to reproduce the issue?

**Comment by IGI-111** [comment]
Sorry I didn't paste this correctly, it should be a `script` not a `contract`.

This should fail correctly:
```sway
script;

abi Abi1 {
    fn foo() -> b256;
}

abi Abi2{
    fn bar() -> u64;
}

pub fn main() {
    let contract_1 = abi(Abi1, b256::min());
    const invalid_const = contract_1.foo();
    let contract_2 = abi(Abi2, invalid_const);
    let invalid = contract_2.bar();
    log(invalid);
}
```
