### ISSUE TITLE
Configurables get elided if only used in LDC

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#5691]
For #5579 we want to let devs build proxies that may look like this:

```sway
contract;

use std::constants::ZERO_B256;
use std::execution::run_external;

configurable {
    TARGET: ContractId = ContractId::from(ZERO_B256),
}

abi RunExternalTest{
    fn foobar() -> u64;
}

impl RunExternalTest for Contract {
    fn foobar() -> u64 {
        run_external(TARGET)
    }
}

fn run_external(load_target: ContractId) -> ! {
    asm(load_target, word, length, ssp_saved) {
        lw load_target fp i74;
        csiz length load_target;
        move ssp_saved ssp;
        ldc load_target zero length;
        addi word zero i64;
        aloc word;
        sw hp ssp_saved i0;
    }
    __jmp_mem()
}
```

However, because `load_target` isn't used in the result of any method of the contract, the `TARGET` configurable gets optimized away, which makes proper configuration impossible.

This still happens if the return value of `run_external` isn't `!`.

We need to either find a way of telling the compiler that `load_target` is consumed by the jump, or fix a bug in the analysis.

**Comment by vaivaswatha** [comment]
In the example posted, `run_external` gets inlined, and because of that, the compiler figures out that TARGET isn't really used at all. This is because, in `run_external`, we are accessing the parameter in assembly, which the compiler cannot figure out. And after inlining, that access, in fact, becomes incorrect.

Adding `#[inline(never)]` to `run_external` gets `TARGET` into the final ABI JSON as a configurable. But the problem now is that, there's a temp local created in `foobar` for `TARGET` before passing it to `run_external`. This happens because the compiler doesn't know that `run_external` will not modify its argument, so it makes a copy for safety.

The local ends up making `ldc` invalid since `ldc` expects 0 stack usage.
