### ISSUE TITLE
Expand match expressions to encompass enums

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#579]
A large portion of the implementation should already be present. The only thing that should be missing is asm generation. The goal is to be able to desugar enums in match expressions as so:

```
script;

enum X {
    Y: u64,
}

impl core::ops::Ord for X {
    fn eq(self, other: Self) -> bool {
        asm(r1: self, r2: other, r3) {
            eq r3 r2 r1;
            r3: bool
        }
    }
    fn lt(self, other: Self) -> bool {
        asm(r1: self, r2: other, r3) {
            lt r3 r2 r1;
            r3: bool
        }
    }
    fn gt(self, other: Self) -> bool {
        asm(r1: self, r2: other, r3) {
            gt r3 r2 r1;
            r3: bool
        }
    }
}

fn main() -> u64 {
    let x = X::Y(42);

    match x {
        X::Y(hi) => { hi },
        _ => { 24 },
    }
}
```

**Comment by nfurfaro** [comment]
This would be amazing to see completed.
I'm just running into the limitations of what I can do with the `Result` type now and hitting this error:
```
42 |         match self {
43 |             Result::Ok(T) => {
   |             ^^^^^^^^^^^^^ Unimplemented feature: ASM generation has not yet been implemented for this.
```

**Comment by sezna** [comment]
Design
Right now, we could implement this as a series of desugaring algorithms without having to write any new codegen. I see a pretty clear path forward this way. Consider the following example (... denotes irrelevant/omitted code):
## Desugaring examples
(using current codegen and semantics)

```rust
enum Result<T, E> {
    Ok: T,
    Err: E,
}

struct MyStruct {
    a: Option<u64>,
}

enum Option<T> {
    Some: T,
    None: ()
}

fn main() {
    let x = Result::Ok(MyStruct { a: Some(5) })
    match x {
        Result::Ok(MyStruct { a }) => a
        ...
    }
}
```
This match arm could desugar to:
rust
if let Result::Ok(x) {
    let a = x.a;
}
---
Now, consider the more complicated example of additionally desugaring the interior option:
```rust
fn main() {
    let x = Result::Ok(MyStruct { a: Some(5) })
    match x {
        Result::Ok(MyStruct { a: Option::Some(interior_value) }) => interior_value,
        ...
    }
}
```
This match arm could desugar to:
```rust
if let Result::Ok(x) {
    let a = x.a;
    if let Option::Some(x) = a {
        let interior_value = x;
    }
}
```
## Design Doc
We need a design document for discussion because I hear a lot of differing opinions from various contributors about how we should implement this. We should all be on the same page before implementing this.
I know there’s talk of moving towards a more rust-ish approach. I'd like to understand why that would be better than what I currently am perceiving to be the straightest and shortest path forward. I think Rust has a lot of design considerations that we don't need to replicate, e.g. their high-level MIR before LLVM IR, where our IR is basically just the straight up low level LLVM-style IR. If we can avoid extra churn for little gain, that's of course preferable. However, if there are significant advantages to this churn, then we should consider it.

**Comment by emilyaherbert** [comment]
I'm on my phone right now, so forgive any typesetting mistakes.

I believe that the issue with desugaring match expressions to if-lets in the instance of enums is that this would require special casing matches that contain enums. This would mean that match expressions would be handled disjointly in the compiler depending on what they are matching on. Which 1) I believe is confusing to newcomers and not very future-proof, 2) maybe impossible considering that the type information for enums is not available during parsing time, 3) doing this would prevent match expressions with enums from using the existing match expression exhaustivity checker. Due to limitation (2), desugaring match expressions with enums to if-lets would mean that match expressions would need to exist in two separate forms through parsing and through type checking, with some match expression desugaring happening during parse time and some match expression desugaring happening during type checking. Due to limitation number (3), this would require implemention overhead. This design may also lead to duplicated logic is various places, due to the nature of special casing.

Instead, I believe that we should desugar match expressions to if expressions (which we do right now) and desugar if-lets to match expressions (which we do not do right now). The changes involved would be to 1) move match expression desugaring to during type checking (this type of design is not unprecedented, it's in my history on my computer somewhere and can find it for whomever is curious), 2) desugar if-lets to match expressions during parse time, and 3) add downcasting internally to the compiler to allow desugaring of enums (this already exists in some form in the IR). I believe that this design is preferred as it eliminates the problems described above. It does introduce implementation overhead, but I will note that it is not as much implementation as it may seem, as the match expression to if expression desugaring algorithm already exists, as does the match exhaustivity algorithm, as does downcasting in a limited form. The diff for this change will be large, but I believe it is algorithmically not as complicated as it may seem.

**Comment by emilyaherbert** [comment]
(again I'm on my phone)

Also in a more complicated case with multiple interior matches, this would require us to 1) additionally introduce chained if-lets or 2) nest if statements n time for n match arms. This could potentially lead to an if expression that is quite large in size.

**Comment by emilyaherbert** [comment]
(on my phone)

I have also heard some talk about the possibility of desugaring if expressions to match expressions. This would introduce its own challenges. Namely, how would you handle cases in which the conditionals of a large if-else are unrelated (i.e. not every match arm would be able to match on the same pattern, as that might not be what the programmer intended to accomplish).

I will also note that there is precidence for desugaring match expressions to if expressions. Like Scala, Rust (although it's by proxy as they actually use switch statements on MIR), and Alpha Normal Form. It's certainly not a steady rule that Sway follows this same path, but personally I do think it offers a little design guidance. If it shows to be more beneficial to break from this pattern, then Sway should definitely not hold itself to this.

**Comment by emilyaherbert** [comment]
Also I will note that this issue is now a duplicate of #844

**Comment by otrho** [comment]
On one hand I like Alex's proposal, at the high level it seems straight forward.  OTOH, it makes sense to convert `if let`s to matches since they're essentially just matches with 2 arms (or 1 with a no-op catch-all arm).  If there are issues with missing type info for the former then that's obviously a problem.

Converting from `match` to if expressions isn't what I'd call 'desugaring'.  I haven't looked closely enough at the current implementation, but I don't understand how you can introduce the matched identifier to the inner scope without essentially making an `if let`.

The problem of mutiple interior matches producing overly complicated nested `if let`s isn't an issue IMO.  It's bounded and in most cases will be a handful of matches.  Optimising passes may literally reduce most complexity away too.

Compiling `if` to `match` doesn't make sense for Sway IMO.  Well, sure, we could, but there's little point since we're not trying to consolidate on a single conditional mechanism like MIR might be.

**Comment by emilyaherbert** [comment]
Let me provide some examples:

As it currently stands, the compiler desugars match expressions to if expressions. Given this Sway code:

```rust
script;

struct Point {
  x: u64,
  y: u64
}

fn main() {
  let p = Point {
    x: 1u64,
    y: 4u64
  };
  match p {
    Point { x: 0u64, y: 4u64 } => { .. },
    Point { x: 0u64, y } => { .. },
    _ => { .. }
  }
}
```

this desugars to this pseudo-Sway code:

```rust
script;

struct Point {
  x: u64,
  y: u64
}

fn main() {
  let p = Point {
    x: 1u64,
    y: 4u64
  };
  let NEW_NAME = p;
  if NEW_NAME.x == 0u64 && NEW_NAME.y == 4u64 {
    ..
  } else if NEW_NAME.x == 0u64 {
    let y = NEW_NAME.y;
    ..
  } else {

  }
}
```

I propose that we change if-lets to instead desugar to match expressions. Given this Sway code:

```rust
script;

struct Point {
  x: u64,
  y: u64
}

fn main() {
  let p = Point {
    x: 1u64,
    y: 4u64
  };
  if let Point { x: 0u64, y: 4u64 } = p {
    ..
  } else {
    ..
  }
}
```

this would desugar to this Sway code:


```rust
script;

struct Point {
  x: u64,
  y: u64
}

fn main() {
  let p = Point {
    x: 1u64,
    y: 4u64
  };
  match p {
    Point { x: 0u64, y: 4u64 } => { .. },
    _ => { .. }
  }
}
```

which would then desugar to this Sway code: 

```rust
script;

struct Point {
  x: u64,
  y: u64
}

fn main() {
  let p = Point {
    x: 1u64,
    y: 4u64
  };
  let NEW_NAME = p;
  if NEW_NAME.x == 0u64 && NEW_NAME.y == 4u64 {
    ..
  } else {

  }
}
```

and I propose that enums are handled as such. Given this Sway code:

```rust
script;

enum Either {
  Left: u64,
  Right: u64
}

fn main() {
  let v = Either::Left(1u64);
  match v {
    Either::Right(0u64) => { .. },
    Either::Left(0u64) => { .. },
    Either::Left(x) => { .. },
    _ => { .. }
  }
}
```

this desugars to this pseudo-Sway code:

```rust
script;

enum Either {
  Left: u64,
  Right: u64
}

fn main() {
  let v = Either::Left(1u64);
  let NEW_NAME = v;
  if NEW_NAME == Either::Right && (NEW_NAME as Either::Right).0 == 0u64 {
    ..
  } else if NEW_NAME == Either::Left && (NEW_NAME as Either::Left).0 == 0u64 {
    ..
  } else if NEW_NAME == Either::Left {
    let x = (NEW_NAME as Either::Left).0;
    ..
  } else {
    ..
  }
}
```

**Comment by sezna** [comment]
Thanks for the examples. This all makes sense, although I'm not sure about the enums part.
With regards to this code example:
```rust
else if NEW_NAME == Either::Left && (NEW_NAME as Either::Left).0 == 0u64 {
```

This `as` is not yet implemented, of course. So, I'd like to hear what the ideal behavior of it is. If it is like Rust or C, then it would take the exact same bytes and just change the type information in the compiler about those bytes, without safety being checked. I see we then use tuple indexing syntax (`.0`) on this casted type. This is also unimplemented, but, IMO, unnecessary as enums always only ever have one inner field as an invariant. 

So the combination of `as` and `.0` is supposed to essentially remove the `tag` value of the enum and access the content it describes. This action of "remove the tag, grab the inner value" is _exactly_ what `if let` currently does. It isn't even a full pattern-matching implementation like rust; it instead _only_ removes the tag and takes the inner value. 

Considering this behavior is all that is needed for this desugaring algorithm, what you're proposing is that we change the current `if let` syntax to `as.... .0` but preserve its behavior. I don't think introducing _two_ new language concepts instead of zero is necessarily the straightest path forward here, and I'm also not sure about special casing this `.0` tuple syntax.

**Comment by emilyaherbert** [comment]
> This action of "remove the tag, grab the inner value" is _exactly_ what `if let` currently does.

Sorry, I haven't made myself clear. I meant that this will directly take the logic from if-lets and use it for this application. So, yes! I am not proposing that we change any syntax. The code I provided was pseudo-Sway code as I mentioned above. I am proposing that we introduce _no_ new language concepts. I am proposing that we 1) desugar if-lets to match expressions, and 2) change the location in the compiler where match expressions are desugared to if expressions, using 3) the downcasting syntax that was introduced by if-lets.

**Comment by sezna** [comment]
Oh awesome, that makes a lot of sense then. And yes perhaps I took the clearly labeled _pseudo_ sway too literally. 😄 

One final question: I am a little confused by the word _downcast_ here, though, as we are actually not casting at all and instead actually constructing a new value that consists of only the inner type. Is this just a jargon difference or are we talking about different concepts?

**Comment by emilyaherbert** [comment]
I think this blerb describes downcasting really well: https://blog.rust-lang.org/2016/04/19/MIR.html#simplifying-match-expressions

Based on your description, I feel that what Sway does is morally/functionally equivalent to the downcasting described in this link.

**Comment by emilyaherbert** [comment]
In the context of Sway, I have been thinking of downcasting as this:

The original reason for creating this issue is that the type checker would not pass given a simple desugaring of enums. i.e. a naive match expression -> if expression desugaring algorithm might accidentally draw equality between inner variant values of different types. Instead, what is better to do is to desugar by checking the variants (the tags) directly, but then downcasting in order to check the inner variant values. This allows the compiler to pass type checking (+ codegen, etc), then at runtime, the checks to the variants (tags) determines if the inner values will be of the same type.

**Comment by nfurfaro** [comment]
🥳 🎆
