### ISSUE TITLE
Compiler panics `Too many arguments, cannot handle.: Immediate12TooLarge`

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#6075]
Compiler panics with the following error when the fueltoolchain for escrow app in https://github.com/FuelLabs/sway-applications/ is updated to use forc 0.60 instead of 0.59

```thread 'main' panicked at sway-core/src/asm_generation/fuel/functions.rs:121:30:
Too many arguments, cannot handle.: Immediate12TooLarge { val: 5944, span: Span { src (ptr): 0x55d704a05a70, source_id: None, start: 0, end: 0, as_str(): "" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by vaivaswatha** [comment]
@SwayStar123 I tried building the escrow app with the latest `master` branch of Sway. It compiled fine for me. This is how I built it:

`cargo run --bin forc -- build --release -p ../sway-applications/escrow/`

Given that we had some new code size reduction fixes pushed in, can you check again and confirm that this issue is resolved?

Thanks.

**Comment by SwayStar123** [comment]
Yes it works thanks
