### ISSUE TITLE
Incorrect Message Owner Validation in `caller_address` FN Reverts Transaction

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/sway#6485]
The [caller_address](https://github.com/FuelLabs/sway/blob/1bda0e8c9862d04e230abee09f17607c11d9d152/sway-lib-std/src/auth.sw#L142C8-L142C22) function currently has an issue when validating the owners of inputs. Specifically, when validating the owner of a message, the function uses the message sender, but the correct owner of the message is in the field recipient.

This incorrect validation results in the transaction reverting with `val 0x0` when a contract function calls `msg_sender` and the transaction includes a Message Coin within its inputs.

You can see the problematic code here:

https://github.com/FuelLabs/sway/blob/1bda0e8c9862d04e230abee09f17607c11d9d152/sway-lib-std/src/auth.sw#L165-L167

**Comment by LuizAsFight** [comment]
when the user has a message funding the transaction, this breaks the withdraw of erc20 in the bridge as the fungible token [uses msg_sender](https://github.com/FuelLabs/fuel-bridge/blob/fbf3fb1fd9a68fd186ed593e956f3904f1fd7ab9/packages/fungible-token/bridge-fungible-token/implementation/src/main.sw#L167) resulting in a `revert(0)`

**Comment by DefiCake** [comment]
Some questions:
- Can a `Message` be generated by means other than the generation by the PoA when including messages that come from L1?

If the answer above is no, and generation of `Messages` is restricted to PoA:
- Is the `sender`field of a message always a L1 entity?

If the answer above is yes, following the logic:
- Does it make more sense to say that we should be looking at the **message recipient** rather than the sender? The message recipient would always be a fuel entity, which is the owner of the message. Looking into the sender of the message input to derive the `sender of the call` might be more of an idiomatic intuition than the logic thing to do. A L1 entity would never be a call sender.

**Comment by DefiCake** [comment]
As discussed internally:
- Messages can only be generated by the block producer as a result of the message parsing from L1. From this it is derived that the `InputMessage::sender` is always a L1 address
- The owner of a message is its recipient, which is a L2 entity. Thus, we should change the code to check the recipient, not the sender.
