### ISSUE TITLE
Refactor RwLock used in namespaces to be a concurrent slab or safer data structure

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#682]
Right now, via testing and analysis, we know the `RwLock` in `sway-core/src/semantic_analysis/namespace/arena.rs` is _unlikely_ to cause a deadlock. I'd like to refactor it into a concurrent slab or similar to make that impossible.

**Comment by mitchmindtree** [comment]
I wonder if we should consider refactoring `MODULES` away from global state altogether in favour of a `Modules` type that is passed through compilation by argument?

As a part of #796 I'm updating `forc build` to emit the JSON ABI alongside the bytecode. I noticed that if I call `compile_to_ast` to produce the ABI and then `compile_to_bytecode` to produce the bytecode straight after that the produced `forc` exe produces a lot of compilation errors about shadowed symbols and reused names. After checking that this had nothing to do with `dependency_graph` and `source_map` (the only two mutable references passed to the `compile_to_*` functions), I realised there must be some global state behind the scenes, and after some digging came across the `MODULES` arena.

I plan to solve my issue properly by re-using the AST that I produce for the ABI to do the rest of the compilation to bytecode, rather than calling `compile_to_bytecode` afterwards which causes the AST to be built a second time unnecessarily. That said, it would be nice if we could call `compile_to_*` twice within a single process without worrying about what kind of global state side effects might occur behind the scenes. This might be useful if we want to support something like cargo's workspaces one day, or write tests that use multiple build profiles for the same project, or for other build tools that want to call into the `sway-core` library or `forc` for whatever reason.

I'm sure there are ways we could achieve these things while still using a global data structure (e.g. providing a way to reset the state between calls to `compile_to_*`), but it might be worth considering passing the `Modules` arena via argument to make sure its always easy to reason about sway's state effects just by reading the function signatures rather than digging through definitions to find uses of global state.

---

Ahhh I just came across https://github.com/FuelLabs/sway/pull/680 where the arena was introduced. It looks like this was mostly motivated by avoiding memory bloat when creating many scopes - is that right? I realise I'm a little late :sweat_smile: but one possible alternative to a global arena might be to use a `Namespace` composed of more functional/clone-friendly immutable data structures, perhaps using something like the [im](https://crates.io/crates/im) crate. The datastructures exposed by `im` are more similar to the kinds you'd find in pure functional languages, where cloning them just clones a pointer or two (rather than all of the data) - the docs have a really nice write-up on when and why you might want to use them [here](https://docs.rs/im/latest/im/index.html#why-would-i-want-this).

**Comment by otrho** [comment]
Prior to those changes it would take something like 10 mins to run the tests, or longer on CI, and now it's more like a minute.  So we need to keep the faster compile times, but preferably remove the lock.  IMO it doesn't really matter how it's done, as long as we hit those criteria.

I also have longer term plans to formalise the module system into something stricter and distinct, as library functions come to the core via the `initial_namespace` and are inlined into the AST.  This isn't great for optimising, though it's far from high priority and I haven't thought about how it should actually work yet.  But when you talk of mimicking cargo workspaces etc. it twigs my antennae.

**Comment by mitchmindtree** [comment]
>  Prior to those changes it would take something like 10 mins to run the tests, or longer on CI, and now it's more like a minute. So we need to keep the faster compile times, but preferably remove the lock.

Those are some epic wins! I should clarify that I'm happy to see the `Arena` stay (especially if it's such magic sauce) - it's more that it's currently global state that I see causing issues down the road, whether it's disguised behind a lock or not, for the reasons mentioned above.

On that topic, do we have any compiler benchmarks? If not I might open an issue, it could be handy for keeping track of how compiler performance changes over time.

> I also have longer term plans to formalise the module system into something stricter and distinct

Nicce, looking forward to seeing how it turns out!

**Comment by otrho** [comment]
> On that topic, do we have any compiler benchmarks? If not I might open an issue

That'd be great, if it's not too hard!

**Comment by sezna** [comment]
I had not heard of the `im` crate before, that’s an awesome crate. As we are single threaded in compilation, we may even be able to use `im-rc` for more speed!

The Arena based solution is definitely a bit brute forced with its lazy-static implementation. I’d love to see something that moves away from that — lazy static usage has already caused issues in the SDK where the compiler is run multiple times under the same PID (reusing the lazy static).
