### ISSUE TITLE
Formatter adding `--` with multi-import statements

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#684]
Minimal repro:

```rust
script;
use std::chain::{panic, panic};

fn main() {
}
```

Output of `forc fmt --check`:

```diff
script;
-use std::chain::{panic, panic};
+--use std::chain::{panic,panic};

fn main() {
}
```

**Comment by vnepveu** [comment]
![image](https://user-images.githubusercontent.com/32623452/151719471-509a8704-1e74-49ca-a881-1c8fbcc767ff.png)
The number of added `-` chars matches the number of statements.

**Comment by vnepveu** [comment]
After wayyyyyy too much time spent digging around on the formatter, it turns out that this issue probably comes from the fact that a single `use std::chain::{panic,log_u8}` statement creates 2 root nodes, which from my understanding should not be happening. Tagging this as a compiler issue (because it comes from the parsing).
