### ISSUE TITLE
Proposal for quality-of-life improvements regarding `sway-core` layout

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#846]
Personally, I find the layout of some of the elements of `sway-core` to be counterintuitive with definitions and impls in files and dirs that I would not expect them to be in. Over time I have grown more familiar with the layout but still find myself searching around for things on occasion.

For example, the current layout for `sway-core/src/semantic-analysis/` is:

```bash
.
├── ast_node
│   ├── code_block.rs
│   ├── declaration
│   │   ├── function
│   │   │   └── function_parameter.rs
│   │   ├── function.rs
│   │   └── variable.rs
│   ├── declaration.rs
│   ├── expression
│   │   ├── enum_instantiation.rs
│   │   ├── func_app_instantiation.rs
│   │   ├── mod.rs
│   │   ├── struct_expr_field.rs
│   │   ├── typed_expression
│   │   │   └── method_application.rs
│   │   ├── typed_expression.rs
│   │   └── typed_expression_variant.rs
│   ├── impl_trait.rs
│   ├── mod.rs
│   ├── return_statement.rs
│   └── while_loop.rs
├── namespace
│   └── arena.rs
├── namespace.rs
├── node_dependencies.rs
├── syntax_tree.rs
└── type_check_arguments.rs
```

taking a look at the `ast_node` dir, we can see that it has a subdir `ast_node/declaration/` as well as a file `ast_node/declaration.rs` which actually contains the definition for the `TypedDeclaration` struct. Normally as a Rust dev, I would be expecting the definition of `TypedDeclaration` to be in  `ast_node/declaration/declaration.rs` or in `ast_node/declaration/mod.rs`. And I would expect `ast_node/declaration/mod.rs` to create a flat interface through which all the elements of `ast_node/declaration/` are made available. The same problem exists for `ast_node/expression/typed_expression/` and `ast_node/expression/typed_expression.rs`.

This is a relatively easy change, but it time complex as it involves resolving dependencies issues.

**Comment by otrho** [comment]
The way modules work has changed recently-ish, in an effort to reduce the number of `mod.rs` files everywhere.

It used to be either put a module in `declaration.rs` or put it in `declaration/mod.rs`, one or the other.  Submodules would go under e.g. `declaration/function.rs` or `declaration/function/mod.rs` and be declared in `declaration/mod.rs`.

Now you can put the module in `declaration.rs` _and_ put submodules under `declaration/function.rs` and not use the `mod.rs` file at all.  This is what we've done at some point for `declaration`.   The `declaration/mod.rs` file you list up there doesn't actually exist under `master` at the moment: https://github.com/FuelLabs/sway/tree/master/sway-core/src/semantic_analysis/ast_node/declaration

So I think it's normal now to expect `TypedDeclaration` in `declaration.rs` and only the sub-modules of `declaration` to exist under that directory, i.e., `function` and `variable`, and `function` in turn has a sub-module for `function-parameter`.

No more `mod.rs` files.

**Comment by mitchmindtree** [comment]
I'm in the same boat as you @emilyaherbert - I'm so used to seeing `foo/mod.rs` and everything related to `foo` under the `foo/` directory that I was thrown when navigating through `sway-core`. It took me a few minutes to realise that a bunch of stuff under `semantic_analysis` was not under the `semantic_analysis` dir and that a `semantic_analysis.rs` file existed too heh! I'd only heard of this being a thing a few days ago when chatting to @JoshuaBatty and another Rustacean pal about it.

Personally, I'm a little disappointed at Rust's choice to go down this route. I think the biggest benefit of the classic `foo/mod.rs` convention is how you can kind of see the module hierarchy just from looking at the directory structure, and seeing `mod.rs` was an easy way of spotting the branching point. I guess not too much has changed, but now we have to search for both either `mod.rs` _or_ a file with the same name in the parent directory.

Another small nit is that my editor sorts by directory and then by file, so with the classic `mod.rs` approach the branching module is with the rest of its children, rather than further down the list in the parent directory as with the new approach:

![Screenshot from 2022-02-27 22-42-35](https://user-images.githubusercontent.com/4587373/155881002-94f94fd3-5525-4d36-8f91-80a177fc0d99.png)

Anyways, if this new approach really is the new Rust convention I'm more inclined just do what is conventional. I do wish I was aware of the discussion upstream around all this though - it's funny, the more content you become with the language the less you check RFCs, so you're more likely to miss proposals that go in a less personally favourable direction :smiling_face_with_tear: 

</ :bike: :derelict_house: >

Whatever we decide on going forward, we should probably make it consistent throughout all of the fuel workspaces as I think inconsistency is worse than a less favourable convention.

**Comment by otrho** [comment]
I would regularly get confused as to which file I was looking at as I jumped around the codebase, when I'd have 3 or 4 different files called `mod.rs` open simultaneously, so I prefer the new system.
