### ISSUE TITLE
Document supertraits in the Sway Book

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#854]
Supertraits are now mostly implemented (https://github.com/FuelLabs/sway/pull/835) except for some occasional warnings (See https://github.com/FuelLabs/sway/issues/837). They should now be properly documented in the Sway Book.

**Comment by ControlCplusControlV** [comment]
Do you see this as its own page or as a subsection of the current Traits page?

**Comment by adlerjohn** [comment]
I would see it as a subsection of the Traits page personally.

**Comment by ControlCplusControlV** [comment]
@mohammadfawaz unable to assign myself due to rights but yes I am doing this. I have most of the documentation written but still working on an example (was thinking of using the Ord one which caused this to begin with). I am away atm but will get to it when I get back though so it may not be until next weekend.

**Comment by nfurfaro** [comment]
As part of this work, perhaps you can also wrap up #753 ?

**Comment by ControlCplusControlV** [comment]
Yeah that makes a lot of sense so will try and fix both in the same PR
