### ISSUE TITLE
Formatting tuples in structs

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#903]
The formatter emits the following for a tuple defined inside a struct, which is not very pretty:
```rust
script;

struct S {
    t: (u64,
    u64, u64, u64, u64), 
}

fn main() {
    let s = S {
        t: (0,
        0, 0, 0, 0)
    };
}
```

**Comment by mohammadfawaz** [comment]
@eureka-cpu is this being tracked somewhere for `fmt v2`?

**Comment by eureka-cpu** [comment]
> @eureka-cpu is this being tracked somewhere for `fmt v2`?

I'm aware of it as a possible issue, but I haven't created an issue for it since we're trying to take into account the previous formatter's shortcomings and allow for a clean slate if there are any new issues that arise. This one will be handled inherently though since we format the inner items of a field from the `ItemKind`

**Comment by mohammadfawaz** [comment]
The new formatter turns the above into the following:
```rust
script;

struct S {
    t: (u64, u64, u64, u64, u64),
}

fn main() {
    let s = S {
        t: (0, 0, 0, 0, 0),
    };
}
```
which seems reasonable, so I'm going to close this issue.
